/**
 * Hand Surgery Diagnosis Picklist
 *
 * ~37 structured diagnoses covering ~90% of hand surgery cases.
 * Each diagnosis maps to suggested procedures from procedurePicklist.ts.
 *
 * SNOMED CT codes are from the Clinical Finding hierarchy (<<404684003).
 * Procedure suggestion IDs reference ProcedurePicklistEntry.id values.
 */

import type { DiagnosisPicklistEntry } from "@/types/diagnosis";

// ═══════════════════════════════════════════════════════════════════════════════
// TRAUMA — FRACTURES
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_FRACTURES: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_distal_radius_fx",
    displayName: "Distal radius fracture",
    shortName: "Distal radius #",
    snomedCtCode: "263102004",
    snomedCtDisplay: "Fracture of distal radius (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "Colles",
      "Smith",
      "Barton",
      "distal radius",
      "wrist fracture",
      "DRF",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_distal_radius_orif",
        displayName: "Distal radius ORIF (volar plate)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_distal_radius_crif",
        displayName: "Distal radius CRIF (K-wires / ex-fix)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_metacarpal_fx",
    displayName: "Metacarpal fracture (2nd–5th)",
    shortName: "Metacarpal #",
    snomedCtCode: "65966004",
    snomedCtDisplay: "Fracture of metacarpal bone (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "MC fracture",
      "boxer's fracture",
      "5th metacarpal",
      "metacarpal neck",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_metacarpal_orif",
        displayName: "Metacarpal fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_metacarpal_crif",
        displayName: "Metacarpal fracture CRIF (K-wires)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_fx_metacarpal_crif_ccs",
        displayName: "Metacarpal fracture CRIF (headless compression screw)",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hand_fx_metacarpal_exfix",
        displayName: "Metacarpal fracture external fixation",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_phalanx_fx",
    displayName: "Phalangeal fracture",
    shortName: "Phalanx #",
    snomedCtCode: "263171006",
    snomedCtDisplay: "Fracture of phalanx of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "finger fracture",
      "P1",
      "P2",
      "P3",
      "proximal phalanx",
      "middle phalanx",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_phalanx_orif",
        displayName: "Phalangeal fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_phalanx_crif",
        displayName: "Phalangeal fracture CRIF (K-wires)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_fx_phalanx_crif_ccs",
        displayName: "Phalangeal fracture CRIF (headless compression screw)",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hand_fx_phalanx_exfix",
        displayName: "Phalangeal fracture external fixation",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_scaphoid_fx",
    displayName: "Scaphoid fracture",
    shortName: "Scaphoid #",
    snomedCtCode: "21947006",
    snomedCtDisplay: "Fracture of scaphoid bone (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["scaphoid", "navicular fracture"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_scaphoid_orif",
        displayName: "Scaphoid ORIF (headless screw)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_scaphoid_percutaneous",
        displayName: "Scaphoid percutaneous fixation",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_bennett_fx",
    displayName: "Bennett's fracture",
    shortName: "Bennett's #",
    snomedCtCode: "20527002",
    snomedCtDisplay: "Bennett fracture (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "Bennett",
      "1st metacarpal base fracture",
      "thumb metacarpal",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_bennett",
        displayName: "Bennett's fracture fixation",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_rolando_fx",
    displayName: "Rolando's fracture",
    shortName: "Rolando's #",
    snomedCtCode: "30400005",
    snomedCtDisplay: "Rolando fracture (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["Rolando", "comminuted thumb metacarpal base"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_rolando",
        displayName: "Rolando's fracture fixation",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_scaphoid_nonunion",
    displayName: "Scaphoid nonunion",
    snomedCtCode: "73936003",
    snomedCtDisplay: "Nonunion of fracture of scaphoid (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: ["scaphoid non-union", "scaphoid pseudarthrosis", "SNAC"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_scaphoid_nonunion_graft",
        displayName: "Scaphoid nonunion repair (bone graft ± fixation)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_prc",
        displayName: "Proximal row carpectomy",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hand_dx_malunion_hand",
    displayName: "Malunion of hand / wrist",
    snomedCtCode: "128308003",
    snomedCtDisplay: "Malunion of fracture (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: ["malunion", "malunited fracture", "rotational deformity"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_corrective_osteotomy",
        displayName: "Corrective osteotomy (malunion)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hand_dx_carpal_fracture_other",
    displayName: "Carpal fracture (other than scaphoid)",
    shortName: "Other carpal #",
    snomedCtCode: "33173003",
    snomedCtDisplay: "Fracture of carpal bone (disorder)",
    specialty: "hand_wrist",
    subcategory: "Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "lunate",
      "capitate",
      "hamate",
      "trapezium",
      "triquetrum",
      "pisiform",
      "carpal fracture",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_carpal_orif",
        displayName: "Carpal fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_carpal_crif",
        displayName: "Carpal fracture CRIF (K-wires)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hand_dx_crush_injury",
    displayName: "Crush injury of hand",
    shortName: "Hand crush",
    snomedCtCode: "125667009",
    snomedCtDisplay: "Crush injury (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "crush",
      "degloving",
      "mangled hand",
      "press injury",
      "industrial",
    ],
    suggestedProcedures: [],
    sortOrder: 10,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// TRAUMA — TENDONS
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_TENDON_INJURIES: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_flexor_tendon_lac",
    displayName: "Flexor tendon laceration",
    shortName: "Flexor tendon lac",
    snomedCtCode: "283588004",
    snomedCtDisplay: "Laceration of flexor tendon of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["FDP", "FDS", "flexor tendon", "zone II", "no man's land"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_flexor_primary",
        displayName: "Flexor tendon repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_extensor_tendon_lac",
    displayName: "Extensor tendon laceration",
    shortName: "Extensor tendon lac",
    snomedCtCode: "283589007",
    snomedCtDisplay: "Laceration of extensor tendon of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["EDC", "extensor tendon", "dorsal laceration"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_extensor_primary",
        displayName: "Extensor tendon repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_fpl_laceration",
    displayName: "FPL tendon laceration",
    shortName: "FPL lac",
    snomedCtCode: "283588004",
    snomedCtDisplay: "Laceration of flexor pollicis longus tendon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["FPL", "flexor pollicis longus", "thumb flexor"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_fpl_repair",
        displayName: "FPL tendon repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_epl_rupture",
    displayName: "EPL tendon rupture",
    shortName: "EPL rupture",
    snomedCtCode: "48188001",
    snomedCtDisplay: "Rupture of extensor pollicis longus tendon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "EPL",
      "extensor pollicis longus",
      "thumb extension loss",
      "EIP transfer",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_epl_rupture_repair",
        displayName: "EPL rupture — EIP transfer",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_mallet_finger",
    displayName: "Mallet finger",
    snomedCtCode: "48574002",
    snomedCtDisplay: "Mallet finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "mallet",
      "DIP extensor",
      "baseball finger",
      "drop finger",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_mallet_finger",
        displayName: "Mallet finger repair / splinting",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_boutonniere",
    displayName: "Boutonnière deformity",
    snomedCtCode: "29750009",
    snomedCtDisplay: "Boutonniere deformity of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["boutonniere", "central slip", "PIP flexion"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_boutonniere_reconstruction",
        displayName: "Boutonnière repair / correction",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_swan_neck",
    displayName: "Swan neck deformity",
    snomedCtCode: "50389003",
    snomedCtDisplay: "Swan neck deformity of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["swan neck", "PIP hyperextension"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_swan_neck_correction",
        displayName: "Swan neck correction",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hand_dx_sagittal_band_rupture",
    displayName: "Sagittal band rupture (MCP)",
    shortName: "Sagittal band rupture",
    snomedCtCode: "239179000",
    snomedCtDisplay: "Rupture of sagittal band (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["sagittal band", "extensor subluxation", "MCP"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_sagittal_band_repair",
        displayName: "Sagittal band repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hand_dx_jersey_finger",
    displayName: "Jersey finger (FDP avulsion)",
    shortName: "Jersey finger",
    snomedCtCode: "283588004",
    snomedCtDisplay: "Avulsion of flexor digitorum profundus tendon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["jersey finger", "FDP avulsion", "Leddy", "ring finger"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_fdp_avulsion_repair",
        displayName: "FDP avulsion repair (Leddy-Packer)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hand_dx_bony_mallet",
    displayName: "Bony mallet finger (fracture)",
    shortName: "Bony mallet",
    snomedCtCode: "48188001",
    snomedCtDisplay: "Mallet finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tendon Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "bony mallet",
      "mallet fracture",
      "DIP fracture",
      "terminal extensor",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_mallet_finger",
        displayName: "Mallet finger splinting / fixation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_disloc_pip_extension_block_kwire",
        displayName: "Extension block K-wire fixation",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 10,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// TRAUMA — NERVES
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_NERVE_INJURIES: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_digital_nerve_lac",
    displayName: "Digital nerve laceration",
    shortName: "Digital nerve lac",
    snomedCtCode: "283013008",
    snomedCtDisplay: "Laceration of digital nerve (disorder)",
    specialty: "hand_wrist",
    subcategory: "Nerve Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["digital nerve", "proper digital", "common digital"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_nerve_digital_repair",
        displayName: "Digital nerve repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_median_nerve_lac",
    displayName: "Median nerve laceration",
    shortName: "Median nerve lac",
    snomedCtCode: "283018004",
    snomedCtDisplay: "Laceration of median nerve (disorder)",
    specialty: "hand_wrist",
    subcategory: "Nerve Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["median nerve", "wrist laceration median"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_nerve_median_repair",
        displayName: "Median nerve repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_nerve_graft",
        displayName: "Nerve graft",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_ulnar_nerve_lac",
    displayName: "Ulnar nerve laceration",
    shortName: "Ulnar nerve lac",
    snomedCtCode: "283019007",
    snomedCtDisplay: "Laceration of ulnar nerve (disorder)",
    specialty: "hand_wrist",
    subcategory: "Nerve Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["ulnar nerve", "wrist laceration ulnar"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_nerve_ulnar_repair",
        displayName: "Ulnar nerve repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_nerve_graft",
        displayName: "Nerve graft",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_radial_nerve_lac",
    displayName: "Radial nerve / PIN / SRN injury",
    shortName: "Radial nerve injury",
    snomedCtCode: "283020001",
    snomedCtDisplay: "Injury of radial nerve (disorder)",
    specialty: "hand_wrist",
    subcategory: "Nerve Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "radial nerve",
      "PIN",
      "posterior interosseous nerve",
      "SRN",
      "wrist drop",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_nerve_radial_repair",
        displayName: "Radial nerve / PIN / SRN repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_nerve_transfer",
        displayName: "Nerve transfer (distal)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_dbun_injury",
    displayName: "Dorsal branch of ulnar nerve injury",
    shortName: "DBUN injury",
    snomedCtCode: "283019007",
    snomedCtDisplay: "Injury of dorsal branch of ulnar nerve (disorder)",
    specialty: "hand_wrist",
    subcategory: "Nerve Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "DBUN",
      "dorsal ulnar",
      "dorsal branch",
      "dorsal sensory ulnar",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_nerve_ulnar_repair",
        displayName: "Ulnar nerve repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_nerve_neuroma_excision",
        displayName: "Neuroma excision",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 5,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// TRAUMA — SOFT TISSUE / FINGERTIP
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_SOFT_TISSUE: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_complex_laceration",
    displayName: "Complex hand / wrist laceration",
    shortName: "Complex laceration",
    snomedCtCode: "284003005",
    snomedCtDisplay: "Open wound of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "spaghetti wrist",
      "complex laceration",
      "multiple tendon",
      "multiple structure",
      "glass injury",
      "knife wound",
      "saw injury",
      "skill saw",
      "table saw",
    ],
    suggestedProcedures: [],
    sortOrder: 0,
  },
  {
    id: "hand_dx_fingertip_injury",
    displayName: "Fingertip injury / amputation",
    shortName: "Fingertip injury",
    snomedCtCode: "284003005",
    snomedCtDisplay: "Injury of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "fingertip",
      "pulp loss",
      "tip amputation",
      "Allen classification",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_vy_advancement",
        displayName: "V-Y advancement flap (fingertip)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_cov_cross_finger",
        displayName: "Cross-finger flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_cov_moberg",
        displayName: "Moberg advancement flap",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hand_cov_skin_graft",
        displayName: "Skin graft to hand (STSG / FTSG)",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_digital_amputation",
    displayName: "Digital amputation (replantable)",
    shortName: "Digit amputation",
    snomedCtCode: "30998006",
    snomedCtDisplay: "Traumatic amputation of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "replantation",
      "amputated finger",
      "severed finger",
      "ring avulsion",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_replantation",
        displayName: "Digital replantation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_cov_revascularisation",
        displayName: "Digital revascularisation",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_nail_bed_injury",
    displayName: "Nail bed injury",
    snomedCtCode: "283028008",
    snomedCtDisplay: "Nail bed injury (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["nail bed", "subungual haematoma", "nail avulsion"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_nail_bed_repair",
        displayName: "Nail bed repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_hand_degloving",
    displayName: "Hand / finger degloving injury",
    snomedCtCode: "283681000",
    snomedCtDisplay: "Degloving injury of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["degloving", "ring avulsion", "Urbaniak"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_skin_graft",
        displayName: "Skin graft to hand",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_cov_free_flap",
        displayName: "Free flap to hand",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_cov_homodigital_island",
        displayName: "Homodigital island flap",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_digital_amputation_nonreplantable",
    displayName: "Digital amputation — non-replantable (terminalisation)",
    shortName: "Non-replantable amputation",
    snomedCtCode: "30998006",
    snomedCtDisplay: "Amputation of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "terminalisation",
      "non-replantable",
      "amputation",
      "revision amputation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_amp_terminalisation",
        displayName: "Terminalisation / revision amputation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_amp_revision_stump",
        displayName: "Stump revision / remodelling",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_thumb_amputation",
    displayName: "Thumb amputation",
    shortName: "Thumb amputation",
    snomedCtCode: "30998006",
    snomedCtDisplay: "Amputation of thumb (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "thumb amputation",
      "thumb replant",
      "pollicisation",
      "toe-to-thumb",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_replantation",
        displayName: "Digital replantation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_amp_terminalisation",
        displayName: "Terminalisation",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_cov_toe_to_thumb",
        displayName: "Toe-to-thumb transfer",
        isDefault: false,
        isConditional: true,
        conditionDescription: "Secondary reconstruction if not replantable",
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hand_cov_pollicisation",
        displayName: "Pollicisation (index to thumb)",
        isDefault: false,
        isConditional: true,
        conditionDescription: "If MCP/CMC level lost",
        sortOrder: 4,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_multiple_digit_amputation",
    displayName: "Multiple digit amputation",
    shortName: "Multiple digit amputation",
    snomedCtCode: "30998006",
    snomedCtDisplay: "Amputation of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["multiple digits", "multi-digit amputation", "replant"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_replantation",
        displayName: "Digital replantation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_amp_terminalisation",
        displayName: "Terminalisation (non-viable digits)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hand_dx_hand_amputation",
    displayName: "Hand / wrist amputation (major replant)",
    shortName: "Hand amputation",
    snomedCtCode: "34731002",
    snomedCtDisplay: "Amputation of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "hand amputation",
      "wrist amputation",
      "major replant",
      "forearm amputation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_recon_major_replantation",
        displayName: "Major replantation (hand / wrist / forearm)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hand_dx_ring_avulsion",
    displayName: "Ring avulsion injury",
    shortName: "Ring avulsion",
    snomedCtCode: "283020001",
    snomedCtDisplay: "Ring avulsion injury (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "ring avulsion",
      "Urbaniak",
      "degloving ring",
      "avulsion injury",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cov_revascularisation",
        displayName: "Digital revascularisation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_cov_replantation",
        displayName: "Digital replantation",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_amp_terminalisation",
        displayName: "Terminalisation",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 9,
  },
  // NOTE: hand_dx_high_pressure_injection and hand_dx_fight_bite moved to HAND_DX_ACUTE
  {
    id: "hand_dx_compartment_syndrome_hand",
    displayName: "Compartment syndrome of hand",
    shortName: "Hand compartment syndrome",
    snomedCtCode: "111254007",
    snomedCtDisplay: "Compartment syndrome of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Soft Tissue Injuries",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "compartment syndrome",
      "hand compartment",
      "fasciotomy",
      "intrinsic compartment",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_hand_compartment_release",
        displayName: "Hand compartment release",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_other_fasciotomy",
        displayName: "Fasciotomy — forearm / hand",
        isDefault: true,
        sortOrder: 2,
      },
    ],
    sortOrder: 12,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// COMPRESSION NEUROPATHIES
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_COMPRESSION: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_carpal_tunnel",
    displayName: "Carpal tunnel syndrome",
    shortName: "CTS",
    snomedCtCode: "57406009",
    snomedCtDisplay: "Carpal tunnel syndrome (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: true, // Severity + EMG grade in diagnosisStagingConfig
    searchSynonyms: [
      "CTS",
      "median nerve compression",
      "carpal tunnel",
      "tingling fingers",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_ctr_open",
        displayName: "Carpal tunnel release — open",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_comp_ctr_endoscopic",
        displayName: "Carpal tunnel release — endoscopic",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_cubital_tunnel",
    displayName: "Cubital tunnel syndrome",
    shortName: "CuTS",
    snomedCtCode: "72764000",
    snomedCtDisplay: "Cubital tunnel syndrome (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "cubital tunnel",
      "ulnar nerve elbow",
      "ulnar neuropathy",
      "CuTS",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_cubital_insitu",
        displayName: "Cubital tunnel decompression — in situ",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_comp_cubital_transposition",
        displayName: "Cubital tunnel — anterior transposition",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_dequervain",
    displayName: "De Quervain's tenosynovitis",
    shortName: "De Quervain's",
    snomedCtCode: "55473002",
    snomedCtDisplay: "De Quervain disease (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "de Quervain",
      "first compartment",
      "radial styloid",
      "Finkelstein",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_dequervain",
        displayName: "De Quervain's release",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_trigger_finger",
    displayName: "Trigger finger",
    snomedCtCode: "60849009",
    snomedCtDisplay: "Trigger finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: true, // Quinnell grade in diagnosisStagingConfig
    searchSynonyms: [
      "trigger finger",
      "stenosing tenosynovitis",
      "locked finger",
      "A1 pulley",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_trigger_finger",
        displayName: "Trigger finger release (A1 pulley)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_trigger_thumb",
    displayName: "Trigger thumb",
    snomedCtCode: "202855006",
    snomedCtDisplay: "Stenosing tenosynovitis of thumb (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: true, // Quinnell grade
    searchSynonyms: ["trigger thumb", "locked thumb"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_trigger_thumb",
        displayName: "Trigger thumb release",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_guyon",
    displayName: "Guyon's canal syndrome",
    snomedCtCode: "35455005",
    snomedCtDisplay: "Ulnar nerve entrapment at wrist (disorder)",
    specialty: "hand_wrist",
    subcategory: "Compression Neuropathies",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["Guyon's canal", "ulnar tunnel", "ulnar nerve wrist"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_guyon",
        displayName: "Guyon's canal release",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DUPUYTREN'S DISEASE
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_DUPUYTREN: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_dupuytren",
    displayName: "Dupuytren's contracture",
    shortName: "Dupuytren's",
    snomedCtCode: "79426006",
    snomedCtDisplay: "Dupuytren contracture of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dupuytren's Disease",
    clinicalGroup: "elective",
    hasStaging: true, // Tubiana stage in diagnosisStagingConfig
    searchSynonyms: [
      "Dupuytren",
      "palmar fibromatosis",
      "palmar contracture",
      "cord",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_dup_limited_fasciectomy",
        displayName: "Limited fasciectomy",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_dup_needle_fasciotomy",
        displayName: "Needle aponeurotomy / fasciotomy",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_dup_dermofasciectomy",
        displayName: "Dermofasciectomy + FTSG",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hand_dup_collagenase",
        displayName: "Collagenase injection (Xiapex)",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hand_dup_radical_fasciectomy",
        displayName: "Radical fasciectomy",
        isDefault: false,
        isConditional: true,
        conditionDescription: "For severe recurrence (Tubiana 3–4)",
        conditionStagingMatch: {
          stagingSystemName: "Tubiana Stage",
          matchValues: ["3", "4"],
        },
        sortOrder: 5,
      },
    ],
    sortOrder: 1,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DEGENERATIVE / JOINT
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_JOINT: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_cmc1_oa",
    displayName: "CMC1 osteoarthritis (thumb base OA)",
    shortName: "Thumb OA",
    snomedCtCode: "202363001",
    snomedCtDisplay: "Osteoarthritis of first carpometacarpal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: true,
    searchSynonyms: [
      "thumb base",
      "CMC1",
      "trapezium",
      "Eaton",
      "basal joint arthritis",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_trapeziectomy",
        displayName: "Trapeziectomy ± LRTI",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_cmc1_prosthesis",
        displayName: "CMC1 joint prosthesis",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_sl_tear_acute",
    displayName: "Acute scapholunate ligament tear",
    shortName: "Acute SL tear",
    snomedCtCode: "239185009",
    snomedCtDisplay: "Injury of scapholunate ligament (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "acute SL tear",
      "acute scapholunate tear",
      "SL tear acute",
      "scapholunate ligament tear",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_sl_ligament_repair",
        displayName: "Scapholunate ligament repair / reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_wrist_arthroscopy_ther",
        displayName: "Wrist arthroscopy — therapeutic",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_sl_injury",
    displayName: "Scapholunate ligament injury",
    shortName: "SL injury",
    snomedCtCode: "239185009",
    snomedCtDisplay: "Injury of scapholunate ligament (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "SL ligament",
      "scapholunate",
      "DISI",
      "Terry Thomas sign",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_sl_ligament_repair",
        displayName: "Scapholunate ligament repair / reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_wrist_arthroscopy_ther",
        displayName: "Wrist arthroscopy — therapeutic",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_tfcc_tear_acute",
    displayName: "Acute TFCC tear",
    shortName: "Acute TFCC tear",
    snomedCtCode: "239184008",
    snomedCtDisplay: "Triangular fibrocartilage complex tear (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "acute TFCC tear",
      "TFCC tear acute",
      "acute triangular fibrocartilage tear",
      "traumatic TFCC tear",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_druj_tfcc_repair",
        displayName: "TFCC repair (acute — arthroscopic or open)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_wrist_arthroscopy_ther",
        displayName: "Wrist arthroscopy — therapeutic",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_tfcc_tear",
    displayName: "TFCC tear",
    shortName: "TFCC tear",
    snomedCtCode: "239184008",
    snomedCtDisplay: "Triangular fibrocartilage complex tear (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "TFCC",
      "triangular fibrocartilage",
      "ulnar wrist pain",
      "Palmer",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_tfcc_repair",
        displayName: "TFCC repair / debridement (elective)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_wrist_arthroscopy_ther",
        displayName: "Wrist arthroscopy — therapeutic",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_disloc_druj_tfcc_repair",
        displayName: "TFCC repair (acute — arthroscopic or open)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_kienbock",
    displayName: "Kienböck's disease",
    shortName: "Kienböck's",
    snomedCtCode: "30886002",
    snomedCtDisplay: "Kienbock disease (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: true,
    searchSynonyms: ["Kienbock", "lunate AVN", "lunate necrosis", "Lichtman"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_prc",
        displayName: "Proximal row carpectomy",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_wrist_arthrodesis",
        displayName: "Wrist arthrodesis",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_wrist_oa",
    displayName: "Wrist osteoarthritis (SNAC / SLAC)",
    shortName: "Wrist OA",
    snomedCtCode: "396275006",
    snomedCtDisplay: "Osteoarthritis of wrist (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["SNAC", "SLAC", "wrist arthritis", "wrist OA"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_wrist_arthrodesis",
        displayName: "Wrist arthrodesis (total or partial)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_prc",
        displayName: "Proximal row carpectomy",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_joint_wrist_denervation",
        displayName: "Wrist denervation",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_ucl_thumb",
    displayName: "Thumb UCL injury (Gamekeeper's / Skier's)",
    shortName: "Thumb UCL",
    snomedCtCode: "239227006",
    snomedCtDisplay: "Injury of ulnar collateral ligament of thumb (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["UCL", "gamekeeper", "skier's thumb", "Stener lesion"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_lig_ucl_repair",
        displayName: "UCL repair — thumb MCP",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_lig_ucl_reconstruction",
        displayName: "UCL reconstruction — thumb MCP (chronic)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_joint_mcp_collateral_repair",
        displayName: "MCP collateral ligament repair (generic)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_pip_oa",
    displayName: "PIP joint osteoarthritis",
    shortName: "PIP OA",
    snomedCtCode: "201819000",
    snomedCtDisplay:
      "Osteoarthritis of proximal interphalangeal joint of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "PIP arthritis",
      "PIP OA",
      "mucous cyst",
      "Heberden",
      "Bouchard",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_pip_arthroplasty",
        displayName: "PIP joint arthroplasty",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_pip_arthrodesis",
        displayName: "PIP joint arthrodesis",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 10,
  },
  {
    id: "hand_dx_mcp_oa",
    displayName: "MCP joint osteoarthritis / destruction",
    shortName: "MCP OA",
    snomedCtCode: "201840001",
    snomedCtDisplay:
      "Osteoarthritis of metacarpophalangeal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["MCP arthritis", "MCP OA", "post-traumatic MCP"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_mcp_arthroplasty",
        displayName: "MCP joint arthroplasty",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 11,
  },
  {
    id: "hand_dx_scaphoid_nonunion_elective",
    displayName: "Scaphoid non-union",
    shortName: "Scaphoid non-union",
    snomedCtCode: "263225007",
    snomedCtDisplay: "Non-union of fracture of scaphoid (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: true,
    searchSynonyms: [
      "scaphoid non-union",
      "scaphoid pseudarthrosis",
      "Matti-Russe",
      "vascularised bone graft",
      "1,2 ICSRA",
      "Herbert",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_fx_scaphoid_nonunion_graft",
        displayName: "Scaphoid non-union bone graft",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_elective_vascularised_bone_graft",
        displayName:
          "Vascularised bone graft (1,2 ICSRA / medial femoral condyle)",
        isDefault: false,
        isConditional: true,
        conditionDescription: "AVN present or prior failed grafting",
        sortOrder: 2,
      },
    ],
    sortOrder: 12,
  },
  {
    id: "hand_dx_druj_instability_chronic",
    displayName: "Chronic DRUJ instability",
    shortName: "DRUJ instability",
    snomedCtCode: "239166008",
    snomedCtDisplay: "Instability of distal radioulnar joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "DRUJ instability",
      "chronic DRUJ",
      "TFCC reconstruction",
      "Sauve-Kapandji",
      "ulnar head replacement",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_elective_druj_reconstruction",
        displayName: "DRUJ stabilisation / reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_elective_sauve_kapandji",
        displayName: "Sauvé-Kapandji procedure",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_elective_darrach",
        displayName: "Darrach procedure (distal ulna excision)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 13,
  },
  {
    id: "hand_dx_preiser",
    displayName: "Preiser's disease (scaphoid AVN)",
    shortName: "Preiser's",
    snomedCtCode: "30886002",
    snomedCtDisplay: "Avascular necrosis of scaphoid (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["Preiser", "scaphoid AVN", "scaphoid necrosis"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_prc",
        displayName: "Proximal row carpectomy",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_elective_four_corner_fusion",
        displayName: "Scaphoid excision + 4-corner fusion",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 14,
  },
  {
    id: "hand_dx_dip_oa",
    displayName: "DIP joint osteoarthritis / mucous cyst",
    shortName: "DIP OA / mucous cyst",
    snomedCtCode: "201825006",
    snomedCtDisplay:
      "Osteoarthritis of distal interphalangeal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Joint & Degenerative",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "DIP arthritis",
      "DIP OA",
      "mucous cyst",
      "Heberden's node",
      "dorsal digital cyst",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_dip_arthrodesis",
        displayName: "DIP arthrodesis",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_elective_mucous_cyst_excision",
        displayName: "Mucous cyst excision ± osteophyte removal",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 15,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// DISLOCATIONS
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_DISLOCATIONS: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_pip_dislocation_dorsal",
    displayName: "PIP joint dislocation — dorsal",
    shortName: "PIP dorsal dislocation",
    snomedCtCode: "239178008",
    snomedCtDisplay:
      "Dislocation of proximal interphalangeal joint of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "PIP dislocation",
      "dorsal dislocation",
      "finger dislocation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_pip_cr",
        displayName: "PIP closed reduction + splinting",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_disloc_pip_extension_block_kwire",
        displayName: "Extension block K-wire (Ishiguro)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_pip_dislocation_volar",
    displayName: "PIP joint dislocation — volar",
    shortName: "PIP volar dislocation",
    snomedCtCode: "239178008",
    snomedCtDisplay:
      "Dislocation of proximal interphalangeal joint of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "PIP volar dislocation",
      "central slip",
      "volar dislocation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_pip_cr",
        displayName: "PIP closed reduction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_tend_central_slip_repair",
        displayName: "Central slip repair",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_pip_fracture_dislocation",
    displayName: "PIP fracture-dislocation",
    shortName: "PIP #-dislocation",
    snomedCtCode: "263207003",
    snomedCtDisplay: "Fracture-dislocation of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "PIP fracture dislocation",
      "pilon fracture",
      "volar lip",
      "dorsal lip",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_pip_extension_block_kwire",
        displayName: "Extension block K-wire (Ishiguro)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_disloc_pip_volar_plate_arthroplasty",
        displayName: "Volar plate arthroplasty (PIP)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_disloc_pip_hemihamate",
        displayName: "Hemi-hamate arthroplasty",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_mcp_dislocation_simple",
    displayName: "MCP joint dislocation — simple (reducible)",
    shortName: "MCP dislocation",
    snomedCtCode: "239173003",
    snomedCtDisplay: "Dislocation of metacarpophalangeal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["MCP dislocation", "simple dislocation"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_mcp_cr",
        displayName: "MCP closed reduction",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_mcp_dislocation_complex",
    displayName: "MCP joint dislocation — complex / irreducible (Kaplan)",
    shortName: "Complex MCP dislocation",
    snomedCtCode: "239173003",
    snomedCtDisplay: "Dislocation of metacarpophalangeal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "complex MCP dislocation",
      "irreducible",
      "Kaplan",
      "volar plate interposition",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_mcp_open_reduction",
        displayName: "MCP open reduction",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_cmc_dislocation",
    displayName: "CMC joint dislocation / fracture-dislocation (2nd–5th)",
    shortName: "CMC dislocation",
    snomedCtCode: "72081002",
    snomedCtDisplay: "Dislocation of carpometacarpal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "CMC dislocation",
      "carpometacarpal dislocation",
      "CMC fracture dislocation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_cmc_crif",
        displayName: "CMC reduction + K-wire fixation",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_thumb_cmc_dislocation",
    displayName: "Thumb CMC dislocation",
    shortName: "Thumb CMC dislocation",
    snomedCtCode: "72081002",
    snomedCtDisplay: "Dislocation of first carpometacarpal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "thumb CMC",
      "thumb base dislocation",
      "Bennett dislocation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_cmc_crif",
        displayName: "CMC reduction + K-wire fixation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_bennett",
        displayName: "Bennett's fracture CRIF",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hand_dx_perilunate_dislocation",
    displayName: "Perilunate dislocation",
    shortName: "Perilunate dislocation",
    snomedCtCode: "58610006",
    snomedCtDisplay: "Perilunate dislocation (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "perilunate",
      "greater arc",
      "carpal dislocation",
      "Mayfield",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_perilunate_orif",
        displayName: "Perilunate open reduction + ligament repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hand_dx_transscaphoid_perilunate",
    displayName: "Trans-scaphoid perilunate fracture-dislocation",
    shortName: "Trans-scaphoid perilunate",
    snomedCtCode: "263148004",
    snomedCtDisplay:
      "Trans-scaphoid perilunate fracture dislocation (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "trans-scaphoid perilunate",
      "greater arc injury",
      "scaphoid perilunate",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_perilunate_orif",
        displayName: "Perilunate open reduction + ligament repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_fx_scaphoid_orif",
        displayName: "Scaphoid ORIF",
        isDefault: true,
        sortOrder: 2,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hand_dx_lunate_dislocation",
    displayName: "Lunate dislocation",
    shortName: "Lunate dislocation",
    snomedCtCode: "72553001",
    snomedCtDisplay: "Dislocation of lunate (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "lunate dislocation",
      "volar lunate",
      "spilled teacup",
      "Mayfield IV",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_perilunate_orif",
        displayName: "Open reduction + ligament repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 10,
  },
  {
    id: "hand_dx_druj_dislocation",
    displayName: "DRUJ dislocation / instability (acute)",
    shortName: "DRUJ dislocation",
    snomedCtCode: "239166008",
    snomedCtDisplay: "Dislocation of distal radioulnar joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Dislocations",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["DRUJ", "distal radioulnar", "DRUJ instability", "TFCC"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_disloc_druj_reduction_kwire",
        displayName: "DRUJ reduction + K-wire stabilisation",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_disloc_druj_tfcc_repair",
        displayName: "TFCC repair (acute)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 11,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ELECTIVE TENDON
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_ELECTIVE_TENDON: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_chronic_boutonniere",
    displayName: "Chronic boutonnière deformity",
    shortName: "Chronic boutonnière",
    snomedCtCode: "29750009",
    snomedCtDisplay: "Boutonniere deformity (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "chronic boutonniere",
      "PIP flexion deformity",
      "central slip deficiency",
      "boutonniere reconstruction",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_boutonniere_reconstruction",
        displayName: "Boutonnière reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_tend_tenolysis",
        displayName: "Tenolysis (extensor)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hand_joint_pip_arthrodesis",
        displayName: "PIP arthrodesis (salvage)",
        isDefault: false,
        isConditional: true,
        conditionDescription:
          "If reconstruction not feasible / fixed deformity",
        sortOrder: 3,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_chronic_swan_neck",
    displayName: "Chronic swan-neck deformity",
    shortName: "Swan-neck",
    snomedCtCode: "52070001",
    snomedCtDisplay: "Swan-neck deformity of finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "swan neck",
      "PIP hyperextension",
      "SORL reconstruction",
      "FDS tenodesis",
      "Zancolli",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_swan_neck_correction",
        displayName: "Swan-neck correction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_pip_arthroplasty",
        displayName: "PIP arthroplasty (if joint destruction)",
        isDefault: false,
        isConditional: true,
        conditionDescription: "If joint arthritic / destroyed",
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_epl_rupture_elective",
    displayName: "EPL rupture (attritional / post-fracture)",
    shortName: "EPL rupture",
    snomedCtCode: "239161003",
    snomedCtDisplay:
      "Rupture of extensor pollicis longus tendon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "EPL rupture",
      "extensor pollicis longus",
      "Lister's tubercle",
      "EIP transfer",
      "attritional rupture",
      "post distal radius fracture",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_epl_rupture_repair",
        displayName: "EIP-to-EPL transfer",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_chronic_mallet",
    displayName: "Chronic mallet finger (late presentation)",
    shortName: "Chronic mallet",
    snomedCtCode: "48574002",
    snomedCtDisplay: "Mallet finger (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "chronic mallet",
      "late mallet",
      "mallet reconstruction",
      "Fowler tenotomy",
      "DIP droop",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_mallet_finger",
        displayName: "Mallet finger repair / splintage",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_joint_dip_arthrodesis",
        displayName: "DIP arthrodesis",
        isDefault: true,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_flexor_tendon_adhesion",
    displayName: "Flexor tendon adhesion / stiffness",
    shortName: "Flexor adhesion",
    snomedCtCode: "239172002",
    snomedCtDisplay: "Adhesion of flexor tendon of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "tendon adhesion",
      "flexor adhesion",
      "tenolysis",
      "stiff finger",
      "post-repair stiffness",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_tenolysis",
        displayName: "Flexor tenolysis",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_extensor_tendon_adhesion",
    displayName: "Extensor tendon adhesion / stiffness",
    shortName: "Extensor adhesion",
    snomedCtCode: "239172002",
    snomedCtDisplay: "Adhesion of extensor tendon of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "extensor adhesion",
      "extensor tenolysis",
      "post-fracture stiffness",
      "plate-related adhesion",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_tenolysis",
        displayName: "Extensor tenolysis",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_flexor_tendon_late_reconstruction",
    displayName: "Flexor tendon — late reconstruction",
    shortName: "Late flexor recon",
    snomedCtCode: "41727003",
    snomedCtDisplay:
      "Reconstruction of flexor tendon of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Elective Tendon",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "Hunter rod",
      "staged reconstruction",
      "flexor tendon reconstruction",
      "silicone rod",
      "tendon graft",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_staged_reconstruction",
        displayName:
          "Staged flexor tendon reconstruction (Hunter rod)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_tend_flexor_graft",
        displayName: "Single-stage flexor tendon graft",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// RHEUMATOID HAND
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_RHEUMATOID: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_rheumatoid_mcp",
    displayName: "Rheumatoid MCP joint disease",
    shortName: "RA MCP",
    snomedCtCode: "201771009",
    snomedCtDisplay:
      "Rheumatoid arthritis of metacarpophalangeal joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Rheumatoid Hand",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "rheumatoid MCP",
      "RA MCP",
      "ulnar drift",
      "MCP subluxation",
      "Swanson",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_joint_mcp_arthroplasty",
        displayName: "MCP arthroplasty (Swanson / Avanta)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_rheumatoid_mcp_synovectomy",
        displayName: "MCP synovectomy",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_vaughan_jackson",
    displayName:
      "Extensor tendon rupture — rheumatoid (Vaughan-Jackson)",
    shortName: "Vaughan-Jackson",
    snomedCtCode: "239161003",
    snomedCtDisplay:
      "Rheumatoid rupture of extensor tendon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Rheumatoid Hand",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "Vaughan-Jackson",
      "EDM rupture",
      "EDC rupture",
      "rheumatoid tendon rupture",
      "extensor rupture",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_tend_tendon_transfer",
        displayName: "Tendon transfer (EIP to EDC etc.)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_tend_flexor_graft",
        displayName: "Tendon graft / bridge graft",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_caput_ulnae",
    displayName: "Caput ulnae syndrome",
    shortName: "Caput ulnae",
    snomedCtCode: "201783003",
    snomedCtDisplay:
      "Rheumatoid disease of distal radioulnar joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Rheumatoid Hand",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "caput ulnae",
      "prominent ulna head",
      "dorsal subluxation DRUJ",
      "Darrach",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_elective_darrach",
        displayName: "Darrach procedure",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_elective_sauve_kapandji",
        displayName: "Sauvé-Kapandji procedure",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_rheumatoid_wrist_synovitis",
    displayName: "Rheumatoid wrist / dorsal tenosynovitis",
    shortName: "RA wrist synovitis",
    snomedCtCode: "201783003",
    snomedCtDisplay: "Rheumatoid synovitis of wrist (disorder)",
    specialty: "hand_wrist",
    subcategory: "Rheumatoid Hand",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "rheumatoid wrist",
      "dorsal tenosynovitis",
      "synovectomy",
      "extensor retinaculum",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_rheumatoid_wrist_synovectomy",
        displayName: "Wrist / dorsal tenosynovectomy",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_rheumatoid_nodule",
    displayName: "Rheumatoid nodule (hand / wrist)",
    shortName: "RA nodule",
    snomedCtCode: "33719002",
    snomedCtDisplay: "Rheumatoid nodule (disorder)",
    specialty: "hand_wrist",
    subcategory: "Rheumatoid Hand",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "rheumatoid nodule",
      "RA nodule",
      "subcutaneous nodule",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_rheumatoid_nodule_excision",
        displayName: "Rheumatoid nodule excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// OTHER / TUMOURS
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_OTHER: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_ganglion",
    displayName: "Ganglion cyst",
    shortName: "Ganglion",
    snomedCtCode: "33981008",
    snomedCtDisplay: "Ganglion cyst (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["ganglion", "dorsal wrist lump", "volar wrist ganglion"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_ganglion",
        displayName: "Ganglion excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_gctts",
    displayName: "Giant cell tumour of tendon sheath",
    shortName: "GCTTS",
    snomedCtCode: "134372003",
    snomedCtDisplay: "Giant cell tumor of tendon sheath (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "GCTTS",
      "PVNS",
      "giant cell tumour",
      "tendon sheath tumour",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_gct_excision",
        displayName: "Giant cell tumour excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_hand_tumour",
    displayName: "Hand tumour — other",
    snomedCtCode: "126670009",
    snomedCtDisplay: "Neoplasm of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "enchondroma",
      "glomus tumour",
      "lipoma hand",
      "schwannoma hand",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_tumour_excision",
        displayName: "Hand tumour excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_enchondroma",
    displayName: "Enchondroma (hand / finger)",
    shortName: "Enchondroma",
    snomedCtCode: "307592004",
    snomedCtDisplay: "Enchondroma of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "enchondroma",
      "cartilage tumour",
      "pathological fracture",
      "phalanx tumour",
      "metacarpal tumour",
      "Ollier",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_elective_curettage_bone_graft",
        displayName: "Curettage + bone graft",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_glomus_tumour",
    displayName: "Glomus tumour (subungual)",
    shortName: "Glomus tumour",
    snomedCtCode: "302858001",
    snomedCtDisplay: "Glomus tumor (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "glomus tumour",
      "glomus tumor",
      "subungual tumour",
      "nail bed pain",
      "cold sensitivity tumour",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_elective_glomus_excision",
        displayName: "Glomus tumour excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_lipoma_hand",
    displayName: "Lipoma (hand / wrist)",
    shortName: "Lipoma",
    snomedCtCode: "93163002",
    snomedCtDisplay: "Lipoma of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Tumours & Other",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "lipoma hand",
      "soft tissue lump",
      "fatty tumour",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_tumour_excision",
        displayName: "Tumour excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 7,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CONGENITAL
// ═══════════════════════════════════════════════════════════════════════════════

const HAND_DX_CONGENITAL: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_syndactyly",
    displayName: "Syndactyly",
    snomedCtCode: "373413006",
    snomedCtDisplay: "Syndactyly (disorder)",
    specialty: "hand_wrist",
    subcategory: "Congenital",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "syndactyly",
      "webbed fingers",
      "simple syndactyly",
      "complex syndactyly",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cong_syndactyly",
        displayName: "Syndactyly release",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_polydactyly",
    displayName: "Polydactyly",
    snomedCtCode: "367418001",
    snomedCtDisplay: "Polydactyly (disorder)",
    specialty: "hand_wrist",
    subcategory: "Congenital",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "polydactyly",
      "extra digit",
      "supernumerary digit",
      "preaxial",
      "postaxial",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cong_polydactyly",
        displayName: "Polydactyly excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_thumb_hypoplasia",
    displayName: "Thumb hypoplasia / aplasia",
    snomedCtCode: "30373003",
    snomedCtDisplay: "Hypoplastic thumb (disorder)",
    specialty: "hand_wrist",
    subcategory: "Congenital",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["thumb hypoplasia", "Blauth", "absent thumb"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_cong_thumb_hypoplasia",
        displayName: "Thumb hypoplasia reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_cov_pollicisation",
        displayName: "Pollicisation",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 3,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

// ═══════════════════════════════════════════════════════════════════════════════
// ACUTE HAND — INFECTIONS & NON-TRAUMA EMERGENCIES
// ═══════════════════════════════════════════════════════════════════════════════

export const HAND_DX_ACUTE: DiagnosisPicklistEntry[] = [
  {
    id: "hand_dx_paronychia",
    displayName: "Paronychia (acute)",
    shortName: "Paronychia",
    snomedCtCode: "71906004",
    snomedCtDisplay: "Paronychia (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "paronychia",
      "nail fold infection",
      "nail abscess",
      "periungual abscess",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_acute_paronychia_drainage",
        displayName: "Paronychia drainage",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hand_dx_felon",
    displayName: "Felon (pulp abscess)",
    shortName: "Felon",
    snomedCtCode: "49938003",
    snomedCtDisplay: "Felon (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "felon",
      "pulp abscess",
      "fingertip abscess",
      "pulp space infection",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_acute_felon_drainage",
        displayName: "Felon incision & drainage",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hand_dx_flexor_sheath_infection",
    displayName: "Septic flexor tenosynovitis",
    shortName: "Flexor sheath infection",
    snomedCtCode: "18165001",
    snomedCtDisplay: "Pyogenic tenosynovitis of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: true,
    searchSynonyms: [
      "flexor sheath infection",
      "pyogenic tenosynovitis",
      "septic tenosynovitis",
      "Kanavel",
      "Kanavel's signs",
      "flexor sheath washout",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_flexor_sheath_washout",
        displayName: "Flexor sheath washout",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hand_dx_deep_space_infection",
    displayName: "Deep space infection (thenar / midpalmar / web space)",
    shortName: "Deep space abscess",
    snomedCtCode: "312581004",
    snomedCtDisplay: "Abscess of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "thenar abscess",
      "midpalmar abscess",
      "web space abscess",
      "deep space infection",
      "collar stud abscess",
      "horseshoe abscess",
      "Parona's space",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_infection_washout",
        displayName: "Hand infection — washout / debridement",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hand_dx_septic_arthritis_hand",
    displayName: "Septic arthritis (hand / wrist)",
    shortName: "Septic arthritis",
    snomedCtCode: "372085003",
    snomedCtDisplay: "Septic arthritis of hand joint (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "septic arthritis",
      "septic joint",
      "joint infection",
      "MCP septic",
      "PIP septic",
      "wrist septic",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_acute_joint_washout",
        displayName: "Joint washout — hand / wrist",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hand_dx_animal_bite_hand",
    displayName: "Animal bite (hand / wrist)",
    shortName: "Animal bite",
    snomedCtCode: "283679001",
    snomedCtDisplay: "Animal bite wound of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "dog bite",
      "cat bite",
      "animal bite",
      "bite wound hand",
      "Pasteurella",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_infection_washout",
        displayName: "Bite wound washout / debridement",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hand_dx_necrotising_fasciitis_hand",
    displayName: "Necrotising fasciitis (upper limb)",
    shortName: "Nec fasc",
    snomedCtCode: "52486002",
    snomedCtDisplay: "Necrotizing fasciitis (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "necrotising fasciitis",
      "nec fasc",
      "necrotizing",
      "flesh eating",
      "NSTI",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_infection_washout",
        displayName: "Radical debridement",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_other_fasciotomy",
        displayName: "Fasciotomy",
        isDefault: true,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hand_dx_post_op_infection_hand",
    displayName: "Post-operative wound infection (hand / wrist)",
    shortName: "Post-op infection",
    snomedCtCode: "301769002",
    snomedCtDisplay: "Postoperative wound infection (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "post-op infection",
      "surgical site infection",
      "SSI",
      "wound breakdown",
      "implant infection",
      "metalwork infection",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_infection_washout",
        displayName: "Wound washout / debridement",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hand_dx_osteomyelitis_hand",
    displayName: "Osteomyelitis (hand / wrist)",
    shortName: "Osteomyelitis",
    snomedCtCode: "60168000",
    snomedCtDisplay: "Osteomyelitis (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "osteomyelitis",
      "bone infection",
      "phalanx infection",
      "metacarpal infection",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_infection_washout",
        displayName: "Debridement / sequestrectomy",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 9,
  },
  // ── MOVED FROM TRAUMA (clinicalGroup changed to "acute") ────────────────
  {
    id: "hand_dx_fight_bite",
    displayName: "Fight bite (human bite to MCP)",
    shortName: "Fight bite",
    snomedCtCode: "283680004",
    snomedCtDisplay: "Human bite of hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Hand Infections",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "fight bite",
      "human bite",
      "clenched fist injury",
      "MCP bite",
      "tooth",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_fight_bite_washout",
        displayName: "Fight bite washout + debridement",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 10,
  },
  {
    id: "hand_dx_high_pressure_injection",
    displayName: "High-pressure injection injury",
    shortName: "HPI",
    snomedCtCode: "283682007",
    snomedCtDisplay: "High pressure injection injury (disorder)",
    specialty: "hand_wrist",
    subcategory: "Acute Non-Infection",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "high pressure injection",
      "HPI",
      "paint gun",
      "grease gun",
      "hydraulic",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_hpi_debridement",
        displayName: "HPI debridement",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hand_other_fasciotomy",
        displayName: "Fasciotomy",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 11,
  },
  // ── NON-INFECTION ACUTE ────────────────────────────────────────────────
  {
    id: "hand_dx_foreign_body_hand",
    displayName: "Foreign body (hand / wrist)",
    shortName: "Foreign body",
    snomedCtCode: "297169007",
    snomedCtDisplay: "Foreign body in hand (disorder)",
    specialty: "hand_wrist",
    subcategory: "Acute Non-Infection",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "foreign body",
      "FB",
      "glass",
      "metal",
      "splinter",
      "needle",
      "fish hook",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_other_foreign_body",
        displayName: "Foreign body removal (hand / wrist)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 20,
  },
  {
    id: "hand_dx_acute_carpal_tunnel",
    displayName: "Acute carpal tunnel syndrome",
    shortName: "Acute CTS",
    snomedCtCode: "57406009",
    snomedCtDisplay: "Carpal tunnel syndrome (disorder)",
    specialty: "hand_wrist",
    subcategory: "Acute Non-Infection",
    clinicalGroup: "acute",
    hasStaging: false,
    searchSynonyms: [
      "acute carpal tunnel",
      "post-fracture CTS",
      "acute median nerve compression",
      "acute CTS",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hand_comp_ctr_open",
        displayName: "Carpal tunnel release — open (emergency)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 21,
  },
];

export const HAND_SURGERY_DIAGNOSES: DiagnosisPicklistEntry[] = [
  ...HAND_DX_FRACTURES,
  ...HAND_DX_TENDON_INJURIES,
  ...HAND_DX_NERVE_INJURIES,
  ...HAND_DX_SOFT_TISSUE,
  ...HAND_DX_COMPRESSION,
  ...HAND_DX_DUPUYTREN,
  ...HAND_DX_JOINT,
  ...HAND_DX_ELECTIVE_TENDON,
  ...HAND_DX_RHEUMATOID,
  ...HAND_DX_DISLOCATIONS,
  ...HAND_DX_OTHER,
  ...HAND_DX_CONGENITAL,
  ...HAND_DX_ACUTE,
];

/** Get hand surgery diagnoses grouped by subcategory */
export function getHandSurgerySubcategories(): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const dx of HAND_SURGERY_DIAGNOSES) {
    if (!seen.has(dx.subcategory)) {
      seen.add(dx.subcategory);
      result.push(dx.subcategory);
    }
  }
  return result;
}

/** Get hand surgery diagnoses for a specific subcategory */
export function getHandSurgeryDiagnosesForSubcategory(
  subcategory: string,
): DiagnosisPicklistEntry[] {
  return HAND_SURGERY_DIAGNOSES.filter((dx) => dx.subcategory === subcategory);
}
