/**
 * Head & Neck Diagnosis Picklist
 *
 * ~88 structured diagnoses across 9 subcategories covering H&N practice:
 * - Skin Cancer (site-specific)
 * - Facial Fractures (high determinism)
 * - Facial Nerve (staged with House-Brackmann)
 * - H&N Cancer (staged with TNM AJCC 8th)
 * - Salivary Gland (benign + malignant)
 * - Soft Tissue Trauma
 * - Acquired Deformities
 * - Vascular Malformations
 * - Benign Tumours & Cysts
 *
 * SNOMED CT codes are from the Clinical Finding hierarchy (<<404684003).
 * Procedure suggestion IDs reference ProcedurePicklistEntry.id values.
 */

import type { DiagnosisPicklistEntry } from "@/types/diagnosis";

// ═══════════════════════════════════════════════════════════════════════════════
// SKIN CANCER — H&N sites
// Site-specific diagnoses with site-appropriate reconstruction suggestions.
// The existing skin cancer picklist in General handles non-site-specific entries.
// ═══════════════════════════════════════════════════════════════════════════════

export const HN_DX_SKIN_CANCER: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_skin_lesion_excision_biopsy",
    displayName: "Skin lesion — excision biopsy (awaiting histology)",
    shortName: "Excision biopsy",
    snomedCtCode: "95324001",
    snomedCtDisplay: "Skin lesion (finding)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: false,
    searchSynonyms: [
      "excision biopsy",
      "diagnostic excision",
      "skin lesion",
      "suspicious lesion",
      "awaiting histology",
      "query BCC",
      "query SCC",
      "query melanoma",
      "?BCC",
      "?SCC",
      "?melanoma",
      "unknown",
      "biopsy",
      "excise and wait",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "gen_skin_benign_lesion",
        displayName: "Skin lesion excision (diagnostic)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "gen_skin_biopsy_punch",
        displayName: "Skin biopsy — punch / incisional",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "gen_skin_shave_curette",
        displayName: "Shave excision / curettage",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 0,
  },
  {
    id: "hn_dx_bcc_face",
    displayName: "BCC of face / head / neck",
    shortName: "BCC face",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Basal cell carcinoma of skin of face (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: ["basal cell", "BCC", "rodent ulcer", "face skin cancer"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_bcc_excision",
        displayName: "BCC excision — face / head / neck",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_advancement",
        displayName: "Local advancement flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_local_rotation",
        displayName: "Local rotation flap",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_local_transposition",
        displayName: "Local transposition flap",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_scc_face",
    displayName: "SCC of face / head / neck",
    shortName: "SCC face",
    snomedCtCode: "254651007",
    snomedCtDisplay: "Squamous cell carcinoma of skin of face (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: ["squamous cell", "SCC", "cutaneous SCC", "cSCC"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_scc_excision",
        displayName: "SCC excision — face / head / neck",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_skin_slnb",
        displayName: "Sentinel lymph node biopsy",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_local_advancement",
        displayName: "Local advancement flap",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_melanoma_face",
    displayName: "Melanoma of head / neck",
    shortName: "Melanoma H&N",
    snomedCtCode: "93655004",
    snomedCtDisplay: "Malignant melanoma of skin of face (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: true, // Breslow + ulceration in diagnosisStagingConfig
    hasEnhancedHistology: true,
    searchSynonyms: ["melanoma", "malignant melanoma", "head neck melanoma"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_melanoma_wle",
        displayName: "Melanoma wide local excision — face / head / neck",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_skin_slnb",
        displayName: "Sentinel lymph node biopsy",
        isDefault: true,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_skin_cancer_nose",
    displayName: "Skin cancer of nose (BCC / SCC)",
    shortName: "Skin cancer nose",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Basal cell carcinoma of skin of nose (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: ["nasal BCC", "nasal SCC", "nose cancer", "alar", "dorsum"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_bcc_excision",
        displayName: "Skin cancer excision — nose",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_bilobed",
        displayName: "Bilobed flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_reg_paramedian_forehead",
        displayName: "Paramedian forehead flap",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_recon_nose_partial",
        displayName: "Partial nasal reconstruction",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_nose_ftsg",
        displayName: "Full-thickness skin graft to nose",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_nose_composite_graft",
        displayName: "Composite graft (ear cartilage to alar rim)",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_nose_dorsal_nasal_rieger",
        displayName: "Dorsal nasal flap (Rieger)",
        isDefault: false,
        sortOrder: 7,
      },
      {
        procedurePicklistId: "hn_nose_forehead_3stage",
        displayName: "Paramedian forehead flap — 3 stage",
        isDefault: false,
        sortOrder: 8,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_skin_cancer_ear",
    displayName: "Skin cancer of ear (BCC / SCC)",
    shortName: "Skin cancer ear",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Basal cell carcinoma of skin of ear (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: ["ear BCC", "ear SCC", "auricular", "pinna", "helix"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_bcc_excision",
        displayName: "Skin cancer excision — ear",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_advancement",
        displayName: "Local advancement flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_recon_ear_partial",
        displayName: "Partial ear reconstruction",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_ear_wedge_excision",
        displayName: "Wedge excision of ear",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_ear_antia_buch",
        displayName: "Antia-Buch flap (helical advancement)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_ear_composite_graft",
        displayName: "Composite graft reconstruction (ear)",
        isDefault: false,
        sortOrder: 6,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_skin_cancer_lip",
    displayName: "Skin cancer of lip (BCC / SCC)",
    shortName: "Skin cancer lip",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Squamous cell carcinoma of lip (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: [
      "lip SCC",
      "lip BCC",
      "vermilion",
      "lower lip cancer",
      "upper lip cancer",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_scc_excision",
        displayName: "Skin cancer excision — lip",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_reg_abbe",
        displayName: "Abbe flap (lip switch)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_reg_karapandzic",
        displayName: "Karapandzic flap",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_recon_lip",
        displayName: "Lip reconstruction",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_lip_vermilion_advance",
        displayName: "Vermilion advancement (lip shave)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_lip_bernard_burow",
        displayName: "Bernard-Burow flap (cheek advancement)",
        isDefault: false,
        sortOrder: 6,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_skin_cancer_eyelid",
    displayName: "Skin cancer of eyelid (BCC / SCC)",
    shortName: "Skin cancer eyelid",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Basal cell carcinoma of skin of eyelid (disorder)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    hasEnhancedHistology: true,
    searchSynonyms: [
      "eyelid BCC",
      "eyelid SCC",
      "periorbital",
      "lid margin",
      "medial canthus",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_bcc_excision",
        displayName: "Skin cancer excision — eyelid",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_eyelid_upper",
        displayName: "Upper eyelid reconstruction",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_recon_eyelid_lower",
        displayName: "Lower eyelid reconstruction",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_eyelid_tenzel",
        displayName: "Tenzel semicircular rotation flap",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_eyelid_hughes",
        displayName: "Hughes tarsoconjunctival flap",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_eyelid_cutler_beard",
        displayName: "Cutler-Beard bridge flap",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_eyelid_mustarde",
        displayName: "Mustardé cheek rotation flap",
        isDefault: false,
        sortOrder: 7,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_mohs_defect",
    displayName: "Mohs surgery defect (reconstruction required)",
    shortName: "Mohs defect",
    snomedCtCode: "254701007",
    snomedCtDisplay: "Defect of skin following Mohs surgery (finding)",
    specialty: "head_neck",
    subcategory: "Skin Cancer",
    clinicalGroup: "oncological",
    hasStaging: false,
    searchSynonyms: ["Mohs", "Mohs defect", "post-Mohs", "Mohs reconstruction"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_skin_mohs_defect",
        displayName: "Mohs defect reconstruction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_advancement",
        displayName: "Local advancement flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_local_bilobed",
        displayName: "Bilobed flap",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_reg_paramedian_forehead",
        displayName: "Paramedian forehead flap",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 8,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FACIAL FRACTURES — Highly deterministic
// Includes generic catch-all entries + specific subtypes for audit granularity.
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_FACIAL_FRACTURES: DiagnosisPicklistEntry[] = [
  // ── Generic mandible (catch-all) ──
  {
    id: "hn_dx_fx_mandible",
    displayName: "Mandible fracture",
    shortName: "Mandible #",
    snomedCtCode: "263172003",
    snomedCtDisplay: "Fracture of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["mandible fracture", "jaw fracture", "broken jaw"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_recon_plate",
        displayName: "ORIF — reconstruction plate",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf_arch_bars",
        displayName: "Closed reduction — arch bars IMF",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf_screws",
        displayName: "Closed reduction — MMF screws",
        isDefault: false,
        sortOrder: 6,
      },
    ],
    sortOrder: 1,
  },
  // ── Mandible subtypes ──
  {
    id: "hn_dx_fx_mandible_condyle",
    displayName: "Condylar fracture of mandible",
    shortName: "Condyle #",
    snomedCtCode: "721322005",
    snomedCtDisplay: "Fracture of condyle of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "condyle",
      "condylar",
      "TMJ fracture",
      "subcondylar",
      "intracapsular",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "IMF / closed reduction",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_condyle_orif",
        displayName: "ORIF condyle (open approach)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Condyle ORIF (generic)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_fx_mandible_angle",
    displayName: "Angle fracture of mandible",
    shortName: "Angle #",
    snomedCtCode: "721326008",
    snomedCtDisplay: "Fracture of angle of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["angle", "mandible angle"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_fx_mandible_body",
    displayName: "Body fracture of mandible",
    shortName: "Body #",
    snomedCtCode: "66517001",
    snomedCtDisplay: "Closed fracture of body of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["body", "mandible body"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_recon_plate",
        displayName: "ORIF — reconstruction plate",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_fx_mandible_symphysis",
    displayName: "Symphysis fracture of mandible",
    shortName: "Symphysis #",
    snomedCtCode: "721327004",
    snomedCtDisplay: "Fracture of symphysis of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["symphysis", "chin fracture"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_recon_plate",
        displayName: "ORIF — reconstruction plate",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_fx_mandible_parasymphysis",
    displayName: "Parasymphysis fracture",
    shortName: "Parasymphysis #",
    snomedCtCode: "263172003",
    snomedCtDisplay: "Fracture of parasymphysis of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["parasymphysis"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_recon_plate",
        displayName: "ORIF — reconstruction plate",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_fx_mandible_ramus",
    displayName: "Ramus fracture of mandible",
    shortName: "Ramus #",
    snomedCtCode: "721325007",
    snomedCtDisplay: "Fracture of ramus of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["ramus"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_mandible_orif",
        displayName: "Mandible ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_miniplate",
        displayName: "ORIF — miniplate (Champy)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fx_mandible_orif_recon_plate",
        displayName: "ORIF — reconstruction plate",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fx_mandible_imf",
        displayName: "Mandible IMF / closed reduction",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 7,
  },
  // ── Zygoma ──
  {
    id: "hn_dx_fx_zygoma",
    displayName: "Zygoma fracture",
    shortName: "Zygoma #",
    snomedCtCode: "263176008",
    snomedCtDisplay: "Fracture of zygoma (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "zygoma",
      "zygomatic",
      "malar",
      "cheekbone",
      "ZMC",
      "tripod fracture",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_zygoma_orif",
        displayName: "Zygoma ORIF",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fx_zygoma_gillies",
        displayName: "Zygoma reduction (Gillies approach)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 8,
  },
  // ── Orbit ──
  {
    id: "hn_dx_fx_orbital_floor",
    displayName: "Orbital floor fracture",
    shortName: "Orbital floor #",
    snomedCtCode: "207787008",
    snomedCtDisplay: "Fracture of orbital floor (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "orbital blowout",
      "blowout fracture",
      "orbit fracture",
      "diplopia",
      "enophthalmos",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_orbital_floor",
        displayName: "Orbital floor repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hn_dx_fx_orbital_medial_wall",
    displayName: "Medial orbital wall fracture",
    shortName: "Medial wall #",
    snomedCtCode: "263168002",
    snomedCtDisplay: "Fracture of medial wall of orbit (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["medial wall", "lamina papyracea", "ethmoid"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_orbital_floor",
        displayName: "Orbital wall repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 10,
  },
  // ── Nasal ──
  {
    id: "hn_dx_fx_nasal",
    displayName: "Nasal fracture",
    shortName: "Nasal #",
    snomedCtCode: "263171005",
    snomedCtDisplay: "Fracture of nasal bone (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "nasal fracture",
      "broken nose",
      "nasal bone",
      "septal fracture",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_nasal",
        displayName: "Nasal fracture reduction (MUA)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 11,
  },
  // ── Le Fort (split into I / II / III) ──
  {
    id: "hn_dx_fx_lefort_1",
    displayName: "Le Fort I fracture",
    shortName: "Le Fort I",
    snomedCtCode: "63669006",
    snomedCtDisplay: "Le Fort I fracture (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "Le Fort I",
      "LeFort I",
      "Guerin fracture",
      "horizontal maxillary",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_lefort",
        displayName: "Le Fort fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 12,
  },
  {
    id: "hn_dx_fx_lefort_2",
    displayName: "Le Fort II fracture",
    shortName: "Le Fort II",
    snomedCtCode: "44916009",
    snomedCtDisplay: "Le Fort II fracture (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["Le Fort II", "LeFort II", "pyramidal fracture"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_lefort",
        displayName: "Le Fort fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 13,
  },
  {
    id: "hn_dx_fx_lefort_3",
    displayName: "Le Fort III fracture",
    shortName: "Le Fort III",
    snomedCtCode: "37027003",
    snomedCtDisplay: "Le Fort III fracture (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["Le Fort III", "LeFort III", "craniofacial disjunction"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_lefort",
        displayName: "Le Fort fracture ORIF",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 14,
  },
  // ── Frontal sinus ──
  {
    id: "hn_dx_fx_frontal_sinus",
    displayName: "Frontal sinus fracture",
    shortName: "Frontal sinus #",
    snomedCtCode: "76542006",
    snomedCtDisplay: "Fracture of frontal bone (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "frontal bone",
      "frontal sinus",
      "anterior table",
      "posterior table",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_frontal_sinus",
        displayName: "Frontal sinus fracture repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 15,
  },
  // ── NOE ──
  {
    id: "hn_dx_fx_noe",
    displayName: "Naso-orbito-ethmoidal (NOE) fracture",
    shortName: "NOE #",
    snomedCtCode: "263176008",
    snomedCtDisplay: "Fracture of naso-ethmoidal complex (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "NOE",
      "naso-orbito-ethmoidal",
      "naso-ethmoid",
      "telecanthus",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_noe",
        displayName: "NOE fracture repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 16,
  },
  // ── Panfacial ──
  {
    id: "hn_dx_fx_panfacial",
    displayName: "Panfacial fracture",
    shortName: "Panfacial #",
    snomedCtCode: "4034004",
    snomedCtDisplay:
      "Closed reduction of facial fracture, except mandible (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Fractures",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "panfacial",
      "multiple facial fractures",
      "complex facial trauma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fx_panfacial",
        displayName: "Panfacial fracture repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 17,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// FACIAL NERVE — All staged with House-Brackmann
// Procedure suggestions are intentionally LOOSE — too many variables.
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_FACIAL_NERVE: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_bells_palsy",
    displayName: "Bell's palsy (idiopathic)",
    shortName: "Bell's palsy",
    snomedCtCode: "193093009",
    snomedCtDisplay: "Bell's palsy (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "bells",
      "bell's",
      "idiopathic",
      "facial palsy",
      "idiopathic facial nerve palsy",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_masseteric_transfer",
        displayName: "Masseteric-facial nerve transfer",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_masseteric",
        displayName: "Free gracilis — masseteric innervation",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_nerve_dual_innervation",
        displayName: "Combined CFNG + masseteric (babysitter)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_nerve_static_sling_adm",
        displayName: "Static sling — AlloDerm / ADM",
        isDefault: false,
        sortOrder: 7,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_facial_nerve_palsy",
    displayName: "Facial nerve palsy (unspecified)",
    shortName: "Facial palsy",
    snomedCtCode: "280816001",
    snomedCtDisplay: "Facial palsy (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "facial nerve palsy",
      "facial palsy",
      "VII nerve",
      "seventh nerve",
      "House-Brackmann",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_masseteric_transfer",
        displayName: "Masseteric-facial nerve transfer",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_masseteric",
        displayName: "Free gracilis — masseteric innervation",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_fn_cross_face",
        displayName: "Cross-face nerve graft",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_nerve_dual_innervation",
        displayName: "Combined CFNG + masseteric (babysitter)",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 7,
      },
      {
        procedurePicklistId: "hn_nerve_static_sling_adm",
        displayName: "Static sling — AlloDerm / ADM",
        isDefault: false,
        sortOrder: 8,
      },
      {
        procedurePicklistId: "hn_fn_gold_weight",
        displayName: "Gold weight / lid loading",
        isDefault: false,
        sortOrder: 9,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_traumatic_nerve_injury",
    displayName: "Traumatic facial nerve injury",
    shortName: "Traumatic CN VII",
    snomedCtCode: "53933002",
    snomedCtDisplay: "Traumatic injury to facial nerve (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "trauma",
    hasStaging: true,
    searchSynonyms: [
      "traumatic",
      "facial nerve injury",
      "nerve transection",
      "temporal bone fracture nerve",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_primary_repair",
        displayName: "Facial nerve primary repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_cable_graft",
        displayName: "Facial nerve cable graft",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_cable_graft_great_auricular",
        displayName: "Cable graft — great auricular",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_post_parotidectomy_palsy",
    displayName: "Facial nerve palsy post-parotidectomy",
    shortName: "Post-parotidectomy palsy",
    snomedCtCode: "280816001",
    snomedCtDisplay: "Facial nerve palsy after surgical procedure (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "post-parotidectomy",
      "parotid nerve injury",
      "iatrogenic facial palsy",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_masseteric_transfer",
        displayName: "Masseteric-facial nerve transfer",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_masseteric",
        displayName: "Free gracilis — masseteric innervation",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_nerve_dual_innervation",
        displayName: "Combined CFNG + masseteric (babysitter)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_nerve_static_sling_adm",
        displayName: "Static sling — AlloDerm / ADM",
        isDefault: false,
        sortOrder: 7,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_post_surgical_palsy",
    displayName: "Post-surgical facial nerve palsy",
    shortName: "Post-surgical palsy",
    snomedCtCode: "280816001",
    snomedCtDisplay: "Facial nerve palsy after surgical procedure (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "post-surgical",
      "iatrogenic",
      "post-operative facial palsy",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_masseteric_transfer",
        displayName: "Masseteric-facial nerve transfer",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_masseteric",
        displayName: "Free gracilis — masseteric innervation",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_nerve_dual_innervation",
        displayName: "Combined CFNG + masseteric (babysitter)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_nerve_static_sling_adm",
        displayName: "Static sling — AlloDerm / ADM",
        isDefault: false,
        sortOrder: 7,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_congenital_palsy",
    displayName: "Congenital facial palsy",
    shortName: "Congenital palsy",
    snomedCtCode: "95822006",
    snomedCtDisplay: "Congenital facial nerve palsy (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "congenital",
    hasStaging: true,
    searchSynonyms: ["congenital", "birth palsy", "congenital facial palsy"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fn_cross_face",
        displayName: "Cross-face nerve graft",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_moebius",
    displayName: "Moebius syndrome",
    shortName: "Moebius",
    snomedCtCode: "766987006",
    snomedCtDisplay: "Moebius syndrome (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "congenital",
    hasStaging: true,
    searchSynonyms: [
      "moebius",
      "mobius",
      "cranial nerve VI VII",
      "congenital bilateral facial palsy",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fn_cross_face",
        displayName: "Cross-face nerve graft",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_ramsay_hunt",
    displayName: "Ramsay Hunt syndrome",
    shortName: "Ramsay Hunt",
    snomedCtCode: "21954000",
    snomedCtDisplay: "Ramsay Hunt syndrome (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "ramsay",
      "hunt",
      "herpes zoster",
      "varicella",
      "herpes zoster oticus",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fn_masseteric_transfer",
        displayName: "Masseteric-facial nerve transfer",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fn_free_gracilis",
        displayName: "Free gracilis transfer (facial reanimation)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_masseteric",
        displayName: "Free gracilis — masseteric innervation",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_nerve_gracilis_double",
        displayName: "Free gracilis — double innervation",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "hn_nerve_dual_innervation",
        displayName: "Combined CFNG + masseteric (babysitter)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "hn_fn_static_sling",
        displayName: "Static facial sling",
        isDefault: false,
        sortOrder: 6,
      },
      {
        procedurePicklistId: "hn_nerve_static_sling_adm",
        displayName: "Static sling — AlloDerm / ADM",
        isDefault: false,
        sortOrder: 7,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hn_dx_synkinesis",
    displayName: "Facial synkinesis",
    shortName: "Synkinesis",
    snomedCtCode: "443441000",
    snomedCtDisplay: "Synkinesis (disorder)",
    specialty: "head_neck",
    subcategory: "Facial Nerve",
    clinicalGroup: "reconstructive",
    hasStaging: true,
    searchSynonyms: [
      "synkinesis",
      "involuntary movement",
      "aberrant regeneration",
      "mass movement",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_nerve_botox_synkinesis",
        displayName: "Botulinum toxin for synkinesis",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 9,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// H&N CANCER — For reconstruction context
// Staged with TNM AJCC 8th Ed (except ORN entries)
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_CANCER: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_oral_cavity_scc",
    displayName: "Oral cavity SCC (tongue / floor / buccal)",
    shortName: "Oral SCC",
    snomedCtCode: "363505006",
    snomedCtDisplay: "Malignant neoplasm of oral cavity (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "oral cancer",
      "tongue cancer",
      "floor of mouth",
      "buccal SCC",
      "oral SCC",
      "intraoral",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_oral_tongue_floor",
        displayName: "Oral / tongue / floor of mouth reconstruction",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_recon_mandible",
        displayName: "Mandible reconstruction",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 4,
      },
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap (osteocutaneous)",
        isDefault: false,
        sortOrder: 5,
      },
      {
        procedurePicklistId: "orth_ff_alt",
        displayName: "Free ALT flap",
        isDefault: false,
        sortOrder: 6,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_oral_cavity_ca",
    displayName: "Oral cavity cancer NOS",
    shortName: "Oral Ca",
    snomedCtCode: "363505006",
    snomedCtDisplay: "Malignant neoplasm of oral cavity (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["oral cavity cancer", "mouth cancer", "oral malignancy"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap (osteocutaneous)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_tongue_ca",
    displayName: "Carcinoma of tongue",
    shortName: "Tongue Ca",
    snomedCtCode: "363375006",
    snomedCtDisplay: "Malignant tumour of tongue (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "tongue cancer",
      "tongue carcinoma",
      "oral tongue",
      "base of tongue",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_alt",
        displayName: "Free ALT flap",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_floor_mouth_ca",
    displayName: "Carcinoma of floor of mouth",
    shortName: "FOM Ca",
    snomedCtCode: "363385007",
    snomedCtDisplay: "Malignant tumour of floor of mouth (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["floor of mouth", "FOM cancer", "sublingual"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_oral_tongue_floor",
        displayName: "Floor of mouth reconstruction",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_buccal_ca",
    displayName: "Carcinoma of buccal mucosa",
    shortName: "Buccal Ca",
    snomedCtCode: "363386008",
    snomedCtDisplay: "Malignant tumour of buccal mucosa (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["buccal mucosa", "buccal cancer", "cheek mucosa"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_oropharynx_ca",
    displayName: "Oropharyngeal cancer",
    shortName: "Oropharynx Ca",
    snomedCtCode: "363392002",
    snomedCtDisplay: "Malignant tumour of oropharynx (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "oropharynx",
      "tonsil cancer",
      "HPV positive",
      "p16 positive",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_oropharynx",
        displayName: "Oropharyngeal reconstruction — free flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "orth_ff_alt",
        displayName: "Free ALT flap",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_mandible_tumour",
    displayName: "Mandibular tumour (primary)",
    shortName: "Mandible tumour",
    snomedCtCode: "448668007",
    snomedCtDisplay: "Malignant neoplasm of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "mandible tumour",
      "mandible cancer",
      "jaw tumour",
      "ameloblastoma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_recon_mandible",
        displayName: "Mandible reconstruction",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_mandible_dcia",
        displayName: "Mandible reconstruction — DCIA free flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap (osteocutaneous)",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_maxilla_tumour",
    displayName: "Maxillary tumour / carcinoma",
    shortName: "Maxilla tumour",
    snomedCtCode: "93888008",
    snomedCtDisplay: "Primary malignant neoplasm of maxilla (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["maxilla tumour", "maxillary cancer", "upper jaw tumour"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_maxilla_free_flap",
        displayName: "Maxilla/midface reconstruction — free flap",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hn_dx_maxillary_sinus_ca",
    displayName: "Maxillary sinus carcinoma",
    shortName: "Max sinus Ca",
    snomedCtCode: "363425008",
    snomedCtDisplay: "Malignant tumour of maxillary sinus (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "maxillary sinus",
      "antral carcinoma",
      "paranasal sinus cancer",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_maxilla_free_flap",
        displayName: "Maxilla/midface reconstruction — free flap",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hn_dx_pharynx_ca",
    displayName: "Pharyngeal cancer (for reconstruction)",
    shortName: "Pharynx Ca",
    snomedCtCode: "363507003",
    snomedCtDisplay: "Malignant tumour of pharynx (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "pharyngeal cancer",
      "hypopharynx",
      "nasopharynx",
      "pharynx tumour",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_pharyngoesophageal",
        displayName: "Pharyngoesophageal reconstruction — tubed RFFF",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "orth_ff_alt",
        displayName: "Free ALT flap",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 10,
  },
  {
    id: "hn_dx_larynx_ca",
    displayName: "Laryngeal cancer (for reconstruction)",
    shortName: "Larynx Ca",
    snomedCtCode: "363429002",
    snomedCtDisplay: "Malignant tumour of larynx (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["laryngeal cancer", "larynx tumour", "vocal cord cancer"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_tracheostomy",
        displayName: "Tracheostomy",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "orth_ff_rfff",
        displayName: "Free RFFF (radial forearm free flap)",
        isDefault: false,
        sortOrder: 3,
      },
    ],
    sortOrder: 11,
  },
  // ── ORN (not oncological, not staged with TNM) ──
  {
    id: "hn_dx_orn_mandible",
    displayName: "Osteoradionecrosis of mandible",
    shortName: "ORN mandible",
    snomedCtCode: "109716001",
    snomedCtDisplay: "Osteoradionecrosis of mandible (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "ORN",
      "osteoradionecrosis",
      "radiation necrosis mandible",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_recon_mandible",
        displayName: "Mandible reconstruction",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap (osteocutaneous)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 12,
  },
  {
    id: "hn_dx_orn_maxilla",
    displayName: "Osteoradionecrosis of maxilla",
    shortName: "ORN maxilla",
    snomedCtCode: "109715002",
    snomedCtDisplay: "Osteoradionecrosis of maxilla (disorder)",
    specialty: "head_neck",
    subcategory: "H&N Cancer",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "ORN maxilla",
      "osteoradionecrosis maxilla",
      "radiation necrosis maxilla",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "orth_ff_fibula",
        displayName: "Free fibula flap",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 13,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SALIVARY GLAND — Benign + Malignant
// Malignant entries staged with TNM AJCC 8th Ed
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_SALIVARY_GLAND: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_parotid_tumour",
    displayName: "Parotid tumour",
    shortName: "Parotid tumour",
    snomedCtCode: "126788000",
    snomedCtDisplay: "Neoplasm of parotid gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["parotid", "salivary gland tumour", "parotid mass"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_superficial",
        displayName: "Parotidectomy",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_parotid_pleomorphic",
    displayName: "Pleomorphic adenoma of parotid",
    shortName: "Pleomorphic adenoma",
    snomedCtCode: "255155005",
    snomedCtDisplay: "Pleomorphic adenoma of parotid gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "pleomorphic adenoma",
      "benign mixed tumour",
      "parotid adenoma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_superficial",
        displayName: "Parotidectomy (superficial)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_parotid_warthin",
    displayName: "Warthin tumour (parotid)",
    shortName: "Warthin tumour",
    snomedCtCode: "448211002",
    snomedCtDisplay: "Warthin tumour (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "warthin",
      "papillary cystadenoma lymphomatosum",
      "adenolymphoma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_superficial",
        displayName: "Parotidectomy (superficial)",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_parotid_mucoepidermoid",
    displayName: "Mucoepidermoid carcinoma of parotid",
    shortName: "Mucoepidermoid Ca",
    snomedCtCode: "423793008",
    snomedCtDisplay: "Mucoepidermoid carcinoma of parotid gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["mucoepidermoid", "MEC parotid", "malignant parotid"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_total",
        displayName: "Parotidectomy (total)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_parotid_adenoid_cystic",
    displayName: "Adenoid cystic carcinoma of parotid",
    shortName: "Adenoid cystic Ca",
    snomedCtCode: "422833009",
    snomedCtDisplay: "Adenoid cystic carcinoma of salivary gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["adenoid cystic", "ACC parotid", "cylindroma"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_total",
        displayName: "Parotidectomy (total)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_parotid_acinic_cell",
    displayName: "Acinic cell carcinoma of parotid",
    shortName: "Acinic cell Ca",
    snomedCtCode: "126788000",
    snomedCtDisplay: "Acinic cell carcinoma (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: ["acinic cell", "acinic cell carcinoma"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_total",
        displayName: "Parotidectomy (total)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_parotid_nos",
    displayName: "Parotid tumour NOS",
    shortName: "Parotid NOS",
    snomedCtCode: "126788000",
    snomedCtDisplay: "Neoplasm of parotid gland, unspecified (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "parotid tumour unspecified",
      "parotid lump",
      "parotid mass NOS",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_parotidectomy_superficial",
        displayName: "Parotidectomy",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_submandibular_tumour",
    displayName: "Submandibular gland tumour (benign)",
    shortName: "SMG tumour",
    snomedCtCode: "92415001",
    snomedCtDisplay: "Benign neoplasm of submandibular gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["submandibular", "submandibular gland", "SMG tumour"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_submandibular_gland_excision",
        displayName: "Submandibular gland excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hn_dx_submandibular_malignant",
    displayName: "Malignant neoplasm of submandibular gland",
    shortName: "SMG Ca",
    snomedCtCode: "363380002",
    snomedCtDisplay: "Malignant tumour of submandibular gland (disorder)",
    specialty: "head_neck",
    subcategory: "Salivary Gland",
    clinicalGroup: "oncological",
    hasStaging: true,
    searchSynonyms: [
      "submandibular malignant",
      "submandibular cancer",
      "SMG carcinoma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_submandibular_gland_excision",
        displayName: "Submandibular gland excision",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_neck_dissection_selective",
        displayName: "Neck dissection",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 9,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// SOFT TISSUE TRAUMA — Lacerations, bites, tissue loss
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_SOFT_TISSUE_TRAUMA: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_facial_laceration",
    displayName: "Facial laceration (unspecified)",
    shortName: "Facial lac",
    snomedCtCode: "283545005",
    snomedCtDisplay: "Wound of face (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "laceration",
      "cut",
      "facial wound",
      "forehead laceration",
      "cheek laceration",
      "chin laceration",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_lac_simple",
        displayName: "Facial laceration repair — simple",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Facial laceration repair — complex / layered",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_laceration_lip",
    displayName: "Laceration of lip",
    shortName: "Lip lac",
    snomedCtCode: "283363006",
    snomedCtDisplay: "Laceration of lip (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "lip laceration",
      "lip cut",
      "through-and-through",
      "vermilion border",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Lip laceration repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_recon_lip",
        displayName: "Lip reconstruction",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_laceration_eyelid",
    displayName: "Laceration of eyelid",
    shortName: "Eyelid lac",
    snomedCtCode: "231816006",
    snomedCtDisplay: "Laceration of eyelid (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "eyelid laceration",
      "lid lac",
      "canalicular",
      "periorbital laceration",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_eyelid_lac",
        displayName: "Eyelid laceration repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_laceration_nose",
    displayName: "Laceration of nose",
    shortName: "Nasal lac",
    snomedCtCode: "373602003",
    snomedCtDisplay: "Laceration of nose (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["nose laceration", "nasal laceration", "nose cut"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Nasal laceration repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_laceration_ear",
    displayName: "Laceration of ear",
    shortName: "Ear lac",
    snomedCtCode: "283361008",
    snomedCtDisplay: "Laceration of ear (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "ear laceration",
      "pinna laceration",
      "auricular laceration",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_ear_lac",
        displayName: "Ear laceration repair",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_dog_bite_face",
    displayName: "Dog bite to face",
    shortName: "Dog bite face",
    snomedCtCode: "283682007",
    snomedCtDisplay: "Dog bite wound of face (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["dog bite", "canine bite", "dog attack"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_wound_exploration",
        displayName: "Wound debridement + exploration",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Facial laceration repair — complex / layered",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_animal_bite_face",
    displayName: "Animal bite to face",
    shortName: "Animal bite face",
    snomedCtCode: "418975000",
    snomedCtDisplay: "Animal bite wound of face (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "animal bite",
      "human bite",
      "cat bite",
      "bite wound face",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_wound_exploration",
        displayName: "Wound debridement + exploration",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Facial laceration repair — complex / layered",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_facial_tissue_loss",
    displayName: "Facial soft tissue loss",
    shortName: "Facial tissue loss",
    snomedCtCode: "110071008",
    snomedCtDisplay: "Avulsion of scalp (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["tissue loss", "avulsion", "degloving", "facial defect"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_wound_exploration",
        displayName: "Wound debridement",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_advancement",
        displayName: "Local flap reconstruction",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 8,
  },
  {
    id: "hn_dx_scalp_avulsion",
    displayName: "Scalp avulsion",
    shortName: "Scalp avulsion",
    snomedCtCode: "110071008",
    snomedCtDisplay: "Avulsion of scalp (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: ["scalp avulsion", "scalp degloving", "scalp loss"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_wound_exploration",
        displayName: "Wound debridement",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_scalp_stsg",
        displayName: "Split-thickness skin graft to scalp",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_scalp_ftsg",
        displayName: "Full-thickness skin graft to scalp",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "hn_scalp_tissue_expansion",
        displayName: "Tissue expansion — scalp",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 9,
  },
  {
    id: "hn_dx_complex_facial_wound",
    displayName: "Complex facial wound",
    shortName: "Complex facial wound",
    snomedCtCode: "283545005",
    snomedCtDisplay: "Complex wound of face (disorder)",
    specialty: "head_neck",
    subcategory: "Soft Tissue Trauma",
    clinicalGroup: "trauma",
    hasStaging: false,
    searchSynonyms: [
      "complex wound",
      "composite wound",
      "multi-layer facial injury",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_trauma_facial_lac_complex",
        displayName: "Complex wound repair",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_trauma_facial_wound_exploration",
        displayName: "Wound exploration + debridement",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 10,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// ACQUIRED DEFORMITIES
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_ACQUIRED_DEFORMITIES: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_post_burn_contracture_face",
    displayName: "Post-burn facial contracture",
    shortName: "Burn contracture",
    snomedCtCode: "408294007",
    snomedCtDisplay: "Burn contracture of skin (disorder)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "burn contracture",
      "post-burn",
      "facial contracture",
      "burn scar",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_zplasty",
        displayName: "Z-plasty (contracture release)",
        isDefault: false,
        sortOrder: 2,
      },
      {
        procedurePicklistId: "hn_fat_grafting_face",
        displayName: "Fat grafting to face",
        isDefault: false,
        sortOrder: 3,
      },
      {
        procedurePicklistId: "orth_ftsg",
        displayName: "Full-thickness skin graft",
        isDefault: false,
        sortOrder: 4,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_hypertrophic_scar_face",
    displayName: "Hypertrophic scar of face",
    shortName: "Hypertrophic scar",
    snomedCtCode: "19843006",
    snomedCtDisplay: "Hypertrophic scar (disorder)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: ["hypertrophic scar", "raised scar", "thickened scar"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_local_zplasty",
        displayName: "Z-plasty (scar revision)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_keloid_face",
    displayName: "Keloid scar of face",
    shortName: "Keloid",
    snomedCtCode: "33659008",
    snomedCtDisplay: "Keloid scar (disorder)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: ["keloid", "keloid scar", "cheloid"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_post_traumatic_deformity",
    displayName: "Post-traumatic facial deformity",
    shortName: "Post-trauma deformity",
    snomedCtCode: "95822006",
    snomedCtDisplay: "Post-traumatic deformity of face (disorder)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "post-traumatic deformity",
      "malunion",
      "facial asymmetry trauma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fat_grafting_face",
        displayName: "Fat grafting to face (structural)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_post_surgical_deformity",
    displayName: "Post-surgical facial deformity",
    shortName: "Post-surgical deformity",
    snomedCtCode: "18283000",
    snomedCtDisplay: "Acquired deformity of nose (disorder)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "post-surgical",
      "iatrogenic deformity",
      "surgical deformity",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: false,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_fat_grafting_face",
        displayName: "Fat grafting to face (structural)",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_facial_asymmetry",
    displayName: "Facial asymmetry (acquired)",
    shortName: "Facial asymmetry",
    snomedCtCode: "15253005",
    snomedCtDisplay: "Facial asymmetry (finding)",
    specialty: "head_neck",
    subcategory: "Acquired Deformities",
    clinicalGroup: "reconstructive",
    hasStaging: false,
    searchSynonyms: [
      "facial asymmetry",
      "hemifacial",
      "progressive hemifacial atrophy",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_fat_grafting_face",
        displayName: "Fat grafting to face (structural)",
        isDefault: true,
        sortOrder: 1,
      },
      {
        procedurePicklistId: "hn_scar_revision_face",
        displayName: "Scar revision — face / neck",
        isDefault: false,
        sortOrder: 2,
      },
    ],
    sortOrder: 6,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// VASCULAR MALFORMATIONS
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_VASCULAR_MALFORMATIONS: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_haemangioma_face",
    displayName: "Haemangioma of face",
    shortName: "Haemangioma",
    snomedCtCode: "400210000",
    snomedCtDisplay: "Haemangioma of face (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["haemangioma", "hemangioma", "strawberry naevus"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_infantile_haemangioma",
    displayName: "Infantile haemangioma of face",
    shortName: "Infantile haemangioma",
    snomedCtCode: "416824008",
    snomedCtDisplay: "Infantile haemangioma of face (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["infantile haemangioma", "IH", "propranolol", "PHACES"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_avm_face",
    displayName: "Arteriovenous malformation of face",
    shortName: "AVM face",
    snomedCtCode: "275519006",
    snomedCtDisplay: "Peripheral arteriovenous malformation (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "congenital",
    hasStaging: false,
    searchSynonyms: [
      "AVM",
      "arteriovenous malformation",
      "high-flow malformation",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_venous_malformation_face",
    displayName: "Venous malformation of face",
    shortName: "Venous malformation",
    snomedCtCode: "234124003",
    snomedCtDisplay: "Venous malformation (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "congenital",
    hasStaging: false,
    searchSynonyms: ["venous malformation", "VM", "low-flow malformation"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_lymphatic_malformation",
    displayName: "Lymphatic malformation of face",
    shortName: "Lymphatic malformation",
    snomedCtCode: "234095009",
    snomedCtDisplay: "Lymphatic malformation (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "congenital",
    hasStaging: false,
    searchSynonyms: [
      "lymphatic malformation",
      "LM",
      "macrocystic",
      "microcystic",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_cystic_hygroma",
    displayName: "Cystic hygroma",
    shortName: "Cystic hygroma",
    snomedCtCode: "399882002",
    snomedCtDisplay: "Cystic hygroma (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "congenital",
    hasStaging: false,
    searchSynonyms: ["cystic hygroma", "lymphangioma", "neck mass congenital"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_vascular_malformation",
        displayName: "Excision of vascular malformation — face",
        isDefault: false,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_port_wine_stain",
    displayName: "Port wine stain (face)",
    shortName: "Port wine stain",
    snomedCtCode: "416377005",
    snomedCtDisplay: "Port wine stain of face (disorder)",
    specialty: "head_neck",
    subcategory: "Vascular Malformations",
    clinicalGroup: "congenital",
    hasStaging: false,
    searchSynonyms: [
      "port wine stain",
      "PWS",
      "naevus flammeus",
      "Sturge-Weber",
      "capillary malformation",
    ],
    suggestedProcedures: [],
    sortOrder: 7,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// BENIGN TUMOURS & CYSTS
// ═══════════════════════════════════════════════════════════════════════════════

const HN_DX_BENIGN_TUMOURS_CYSTS: DiagnosisPicklistEntry[] = [
  {
    id: "hn_dx_dermoid_cyst",
    displayName: "Dermoid cyst of face",
    shortName: "Dermoid cyst",
    snomedCtCode: "763220008",
    snomedCtDisplay: "Dermoid cyst of face (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["dermoid", "dermoid cyst", "external angular dermoid"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_other_dermoid_excision",
        displayName: "Dermoid cyst excision",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 1,
  },
  {
    id: "hn_dx_epidermoid_cyst",
    displayName: "Epidermoid cyst of face",
    shortName: "Epidermoid cyst",
    snomedCtCode: "419320008",
    snomedCtDisplay: "Epidermoid cyst of face (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "epidermoid",
      "epidermal inclusion cyst",
      "sebaceous cyst",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 2,
  },
  {
    id: "hn_dx_lipoma_face",
    displayName: "Lipoma of face",
    shortName: "Lipoma face",
    snomedCtCode: "93159009",
    snomedCtDisplay: "Lipoma of face (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["lipoma face", "fatty lump face"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 3,
  },
  {
    id: "hn_dx_lipoma_neck",
    displayName: "Lipoma of neck",
    shortName: "Lipoma neck",
    snomedCtCode: "93160004",
    snomedCtDisplay: "Lipoma of neck (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: [
      "lipoma neck",
      "fatty lump neck",
      "posterior triangle lipoma",
    ],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 4,
  },
  {
    id: "hn_dx_neurofibroma",
    displayName: "Neurofibroma of face",
    shortName: "Neurofibroma",
    snomedCtCode: "404029005",
    snomedCtDisplay: "Neurofibroma (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["neurofibroma", "NF1", "plexiform"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 5,
  },
  {
    id: "hn_dx_pilomatricoma",
    displayName: "Pilomatricoma",
    shortName: "Pilomatricoma",
    snomedCtCode: "274901004",
    snomedCtDisplay: "Pilomatricoma (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["pilomatrixoma", "calcifying epithelioma", "Malherbe"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 6,
  },
  {
    id: "hn_dx_sebaceous_cyst",
    displayName: "Sebaceous cyst of face",
    shortName: "Sebaceous cyst",
    snomedCtCode: "419320008",
    snomedCtDisplay: "Sebaceous cyst of face (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["sebaceous cyst", "pilar cyst", "trichilemmal cyst"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 7,
  },
  {
    id: "hn_dx_keratoacanthoma",
    displayName: "Keratoacanthoma",
    shortName: "Keratoacanthoma",
    snomedCtCode: "254662007",
    snomedCtDisplay: "Keratoacanthoma (disorder)",
    specialty: "head_neck",
    subcategory: "Benign Tumours & Cysts",
    clinicalGroup: "elective",
    hasStaging: false,
    searchSynonyms: ["keratoacanthoma", "KA", "molluscan sebaceum"],
    suggestedProcedures: [
      {
        procedurePicklistId: "hn_excision_benign_tumour",
        displayName: "Excision of benign facial tumour / cyst",
        isDefault: true,
        sortOrder: 1,
      },
    ],
    sortOrder: 8,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

export const HEAD_NECK_DIAGNOSES: DiagnosisPicklistEntry[] = [
  ...HN_DX_SKIN_CANCER,
  ...HN_DX_FACIAL_FRACTURES,
  ...HN_DX_FACIAL_NERVE,
  ...HN_DX_CANCER,
  ...HN_DX_SALIVARY_GLAND,
  ...HN_DX_SOFT_TISSUE_TRAUMA,
  ...HN_DX_ACQUIRED_DEFORMITIES,
  ...HN_DX_VASCULAR_MALFORMATIONS,
  ...HN_DX_BENIGN_TUMOURS_CYSTS,
];

/** Get H&N diagnoses grouped by subcategory */
export function getHeadNeckSubcategories(): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const dx of HEAD_NECK_DIAGNOSES) {
    if (!seen.has(dx.subcategory)) {
      seen.add(dx.subcategory);
      result.push(dx.subcategory);
    }
  }
  return result;
}

/** Get H&N diagnoses for a specific subcategory */
export function getHeadNeckDiagnosesForSubcategory(
  subcategory: string,
): DiagnosisPicklistEntry[] {
  return HEAD_NECK_DIAGNOSES.filter((dx) => dx.subcategory === subcategory);
}
