import { type InsertSnomedRef } from "@shared/schema";

export const vesselSeedData: InsertSnomedRef[] = [
  // LOWER LEG ARTERIES
  {
    snomedCtCode: "181349004",
    displayName: "Anterior tibial artery",
    commonName: "ATA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "181351000",
    displayName: "Posterior tibial artery",
    commonName: "PTA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "181350004",
    displayName: "Peroneal artery",
    commonName: "Fibular artery",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 3,
  },

  // LOWER LEG VEINS
  {
    snomedCtCode: "63507001",
    displayName: "Anterior tibial veins",
    commonName: "Venae comitantes ATA",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "56849005",
    displayName: "Posterior tibial veins",
    commonName: "Venae comitantes PTA",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "32361000",
    displayName: "Peroneal veins",
    commonName: "Fibular veins",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 12,
  },
  {
    snomedCtCode: "60734001",
    displayName: "Great saphenous vein",
    commonName: "GSV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 13,
  },
  {
    snomedCtCode: "7657000",
    displayName: "Small saphenous vein",
    commonName: "SSV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    sortOrder: 14,
  },

  // FOOT ARTERIES
  {
    snomedCtCode: "181353002",
    displayName: "Dorsalis pedis artery",
    commonName: "DPA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "181355009",
    displayName: "Medial plantar artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "181356005",
    displayName: "Lateral plantar artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "181351000",
    displayName: "Posterior tibial artery (at ankle)",
    commonName: "PTA at ankle",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 4,
  },

  // FOOT VEINS
  {
    snomedCtCode: "14944004",
    displayName: "Dorsal venous arch of foot",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "60734001",
    displayName: "Great saphenous vein (at ankle)",
    commonName: "GSV at ankle",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "foot",
    specialty: "free_flap",
    sortOrder: 11,
  },

  // UPPER ARM ARTERIES
  {
    snomedCtCode: "17137000",
    displayName: "Brachial artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "368504007",
    displayName: "Profunda brachii artery",
    commonName: "Deep brachial",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    sortOrder: 2,
  },

  // UPPER ARM VEINS
  {
    snomedCtCode: "20699002",
    displayName: "Brachial veins",
    commonName: "Venae comitantes",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "83215007",
    displayName: "Cephalic vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "76752008",
    displayName: "Basilic vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    sortOrder: 12,
  },

  // FOREARM ARTERIES
  {
    snomedCtCode: "45631007",
    displayName: "Radial artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "44984001",
    displayName: "Ulnar artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "28040004",
    displayName: "Anterior interosseous artery",
    commonName: "AIO",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "38480009",
    displayName: "Posterior interosseous artery",
    commonName: "PIO",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 4,
  },

  // FOREARM VEINS
  {
    snomedCtCode: "50536004",
    displayName: "Radial veins",
    commonName: "Venae comitantes",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "8671006",
    displayName: "Ulnar veins",
    commonName: "Venae comitantes",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "83215007",
    displayName: "Cephalic vein (forearm)",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 12,
  },
  {
    snomedCtCode: "76752008",
    displayName: "Basilic vein (forearm)",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    sortOrder: 13,
  },

  // HAND ARTERIES
  {
    snomedCtCode: "34340008",
    displayName: "Superficial palmar arch",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "33795007",
    displayName: "Deep palmar arch",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "45631007",
    displayName: "Radial artery (at wrist)",
    commonName: "RA at wrist",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "44984001",
    displayName: "Ulnar artery (at wrist)",
    commonName: "UA at wrist",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 4,
  },
  {
    snomedCtCode: "54020004",
    displayName: "Common digital artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 5,
  },
  {
    snomedCtCode: "62944002",
    displayName: "Proper palmar digital artery",
    commonName: "Digital artery",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 6,
  },
  {
    snomedCtCode: "13351009",
    displayName: "First dorsal metacarpal artery",
    commonName: "FDMA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 7,
  },

  // HAND VEINS
  {
    snomedCtCode: "42740004",
    displayName: "Dorsal digital veins of hand",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "77069007",
    displayName: "Dorsal venous network of hand",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "83215007",
    displayName: "Cephalic vein (at wrist)",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 12,
  },
  {
    snomedCtCode: "76752008",
    displayName: "Basilic vein (at wrist)",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "hand",
    specialty: "free_flap",
    sortOrder: 13,
  },

  // HEAD & NECK ARTERIES
  {
    snomedCtCode: "69105007",
    displayName: "Facial artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "74805009",
    displayName: "Superior thyroid artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "43899006",
    displayName: "Superficial temporal artery",
    commonName: "STA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "42258001",
    displayName: "External carotid artery",
    commonName: "ECA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 4,
  },
  {
    snomedCtCode: "57591007",
    displayName: "Transverse cervical artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 5,
  },
  {
    snomedCtCode: "23074001",
    displayName: "Internal mammary artery",
    commonName: "IMA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 6,
  },

  // HEAD & NECK VEINS
  {
    snomedCtCode: "63190004",
    displayName: "External jugular vein",
    commonName: "EJV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "12691009",
    displayName: "Internal jugular vein",
    commonName: "IJV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "70578003",
    displayName: "Facial vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 12,
  },
  {
    snomedCtCode: "6574001",
    displayName: "Superficial temporal vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 13,
  },
  {
    snomedCtCode: "23074001",
    displayName: "Internal mammary vein",
    commonName: "IMV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    sortOrder: 14,
  },

  // BREAST / CHEST WALL VESSELS
  {
    snomedCtCode: "23074001",
    displayName: "Internal mammary artery (internal thoracic artery)",
    commonName: "IMA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "181354005",
    displayName: "Thoracodorsal artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "68455001",
    displayName: "Lateral thoracic artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "31114002",
    displayName: "Thoracoacromial artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 4,
  },
  {
    snomedCtCode: "23074001",
    displayName: "Internal mammary vein (internal thoracic vein)",
    commonName: "IMV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "181356007",
    displayName: "Thoracodorsal vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "83215007",
    displayName: "Cephalic vein (deltopectoral groove)",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "breast_chest",
    specialty: "free_flap",
    sortOrder: 12,
  },

  // THIGH ARTERIES (for groin and thigh recipient sites)
  {
    snomedCtCode: "181347002",
    displayName: "Femoral artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "244316004",
    displayName: "Superficial femoral artery",
    commonName: "SFA",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "244317008",
    displayName: "Profunda femoris artery",
    commonName: "Deep femoral",
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "77453003",
    displayName: "Descending genicular artery",
    commonName: null,
    category: "vessel",
    subcategory: "artery",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 4,
  },

  // THIGH VEINS
  {
    snomedCtCode: "83419000",
    displayName: "Femoral vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "60734001",
    displayName: "Great saphenous vein (thigh)",
    commonName: "GSV",
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "15672000",
    displayName: "Profunda femoris vein",
    commonName: null,
    category: "vessel",
    subcategory: "vein",
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    sortOrder: 12,
  },
];

export const flapTypeSeedData: InsertSnomedRef[] = [
  // Common free flaps with SNOMED CT codes
  {
    snomedCtCode: "234298008",
    displayName: "Anterolateral thigh free flap",
    commonName: "ALT Flap",
    category: "flap",
    subcategory: "fasciocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "234294006",
    displayName: "Deep inferior epigastric perforator flap",
    commonName: "DIEP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "234289000",
    displayName: "Free fibula flap",
    commonName: "Fibula Flap",
    category: "flap",
    subcategory: "osteocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 3,
  },
  {
    snomedCtCode: "234295007",
    displayName: "Free radial forearm flap",
    commonName: "RFFF",
    category: "flap",
    subcategory: "fasciocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 4,
  },
  {
    snomedCtCode: "234296008",
    displayName: "Free latissimus dorsi flap",
    commonName: "LD Flap",
    category: "flap",
    subcategory: "muscle",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 5,
  },
  {
    snomedCtCode: "234297004",
    displayName: "Free gracilis flap",
    commonName: "Gracilis",
    category: "flap",
    subcategory: "muscle",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 6,
  },
  {
    snomedCtCode: "446078000",
    displayName: "Free transverse rectus abdominis myocutaneous flap",
    commonName: "Free TRAM",
    category: "flap",
    subcategory: "myocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 7,
  },
  {
    snomedCtCode: "234300002",
    displayName: "Free superficial inferior epigastric artery flap",
    commonName: "SIEA Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 8,
  },
  {
    snomedCtCode: "234301003",
    displayName: "Free superior gluteal artery perforator flap",
    commonName: "SGAP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 9,
  },
  {
    snomedCtCode: "234302005",
    displayName: "Free inferior gluteal artery perforator flap",
    commonName: "IGAP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 10,
  },
  {
    snomedCtCode: "234303000",
    displayName: "Free scapular flap",
    commonName: "Scapular Flap",
    category: "flap",
    subcategory: "fasciocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 11,
  },
  {
    snomedCtCode: "234304006",
    displayName: "Free parascapular flap",
    commonName: "Parascapular Flap",
    category: "flap",
    subcategory: "fasciocutaneous",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 12,
  },
  {
    snomedCtCode: "234305007",
    displayName: "Free serratus anterior flap",
    commonName: "Serratus Flap",
    category: "flap",
    subcategory: "muscle",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 13,
  },
  {
    snomedCtCode: "234306008",
    displayName: "Free medial sural artery perforator flap",
    commonName: "MSAP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 14,
  },
  {
    snomedCtCode: "234307004",
    displayName: "Free thoracodorsal artery perforator flap",
    commonName: "TDAP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 15,
  },
  {
    snomedCtCode: "234308009",
    displayName: "Free profunda artery perforator flap",
    commonName: "PAP Flap",
    category: "flap",
    subcategory: "perforator",
    anatomicalRegion: null,
    specialty: "free_flap",
    sortOrder: 16,
  },
];

export const donorVesselSeedData: InsertSnomedRef[] = [
  // ALT Flap donor vessels
  {
    snomedCtCode: "244311009",
    displayName: "Descending branch of lateral circumflex femoral artery",
    commonName: "Desc. branch LCFA",
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "alt_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "244312002",
    displayName: "Lateral circumflex femoral artery",
    commonName: "LCFA",
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "alt_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "244313007",
    displayName: "Venae comitantes of LCFA",
    commonName: "LCFA veins",
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "alt_flap",
    specialty: "free_flap",
    sortOrder: 3,
  },

  // DIEP Flap donor vessels
  {
    snomedCtCode: "303413006",
    displayName: "Deep inferior epigastric artery",
    commonName: "DIEA",
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "diep_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "303414000",
    displayName: "Deep inferior epigastric vein",
    commonName: "DIEV",
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "diep_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },

  // Fibula Flap donor vessels
  {
    snomedCtCode: "181350004",
    displayName: "Peroneal artery",
    commonName: "Fibular artery",
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "fibula_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "32361000",
    displayName: "Peroneal veins",
    commonName: "Fibular veins",
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "fibula_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },

  // Radial Forearm Flap donor vessels
  {
    snomedCtCode: "45631007",
    displayName: "Radial artery",
    commonName: null,
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "rfff_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "50536004",
    displayName: "Radial venae comitantes",
    commonName: null,
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "rfff_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },
  {
    snomedCtCode: "83215007",
    displayName: "Cephalic vein",
    commonName: null,
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "rfff_flap",
    specialty: "free_flap",
    sortOrder: 3,
  },

  // Latissimus Dorsi Flap donor vessels
  {
    snomedCtCode: "21814001",
    displayName: "Thoracodorsal artery",
    commonName: null,
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "ld_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "79037004",
    displayName: "Thoracodorsal vein",
    commonName: null,
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "ld_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },

  // Gracilis Flap donor vessels
  {
    snomedCtCode: "244318003",
    displayName: "Medial circumflex femoral artery",
    commonName: "MCFA",
    category: "donor_vessel",
    subcategory: "artery",
    anatomicalRegion: "gracilis_flap",
    specialty: "free_flap",
    sortOrder: 1,
  },
  {
    snomedCtCode: "244319006",
    displayName: "Venae comitantes of MCFA",
    commonName: null,
    category: "donor_vessel",
    subcategory: "vein",
    anatomicalRegion: "gracilis_flap",
    specialty: "free_flap",
    sortOrder: 2,
  },
];

export const compositionOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "comp_fasciocutaneous",
    displayName: "Fasciocutaneous",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 1,
  },
  {
    snomedCtCode: "comp_muscle",
    displayName: "Muscle only",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 2,
  },
  {
    snomedCtCode: "comp_musculocutaneous",
    displayName: "Musculocutaneous",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 3,
  },
  {
    snomedCtCode: "comp_osteocutaneous",
    displayName: "Osteocutaneous",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 4,
  },
  {
    snomedCtCode: "comp_osteomuscular",
    displayName: "Osteomuscular",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 5,
  },
  {
    snomedCtCode: "comp_chimeric",
    displayName: "Chimeric",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 6,
  },
  {
    snomedCtCode: "comp_adipofascial",
    displayName: "Adipofascial",
    commonName: null,
    category: "composition",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 7,
  },
];

export const anatomicalRegionOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "region_lower_leg",
    displayName: "Lower leg",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "lower_leg",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 1,
  },
  {
    snomedCtCode: "region_foot",
    displayName: "Foot",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "foot",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 2,
  },
  {
    snomedCtCode: "region_thigh",
    displayName: "Thigh",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "thigh",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 3,
  },
  {
    snomedCtCode: "region_hand",
    displayName: "Hand",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "hand",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 4,
  },
  {
    snomedCtCode: "region_forearm",
    displayName: "Forearm",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "forearm",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 5,
  },
  {
    snomedCtCode: "region_upper_arm",
    displayName: "Upper arm",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "upper_arm",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 6,
  },
  {
    snomedCtCode: "region_head_neck",
    displayName: "Head & Neck",
    commonName: null,
    category: "anatomical_region",
    subcategory: null,
    anatomicalRegion: "head_neck",
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 7,
  },
];

export const couplingMethodOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "coupling_hand_sewn",
    displayName: "Hand-sewn",
    commonName: null,
    category: "coupling_method",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 1,
  },
  {
    snomedCtCode: "coupling_coupler",
    displayName: "Mechanical coupler",
    commonName: "Coupler",
    category: "coupling_method",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 2,
  },
  {
    snomedCtCode: "coupling_hybrid",
    displayName: "Hybrid (artery hand-sewn, vein coupler)",
    commonName: null,
    category: "coupling_method",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 3,
  },
];

export const anastomosisConfigOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "config_end_to_end",
    displayName: "End-to-end",
    commonName: "E-E",
    category: "anastomosis_config",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 1,
  },
  {
    snomedCtCode: "config_end_to_side",
    displayName: "End-to-side",
    commonName: "E-S",
    category: "anastomosis_config",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 2,
  },
  {
    snomedCtCode: "config_side_to_side",
    displayName: "Side-to-side",
    commonName: "S-S",
    category: "anastomosis_config",
    subcategory: null,
    anatomicalRegion: null,
    specialty: "free_flap",
    codeType: "internal",
    sortOrder: 3,
  },
];

export const comorbidityOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "84114007",
    displayName: "Acquired brain injury",
    commonName: "ABI",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 1,
  },
  {
    snomedCtCode: "49436004",
    displayName: "Atrial fibrillation",
    commonName: "AF",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 2,
  },
  {
    snomedCtCode: "7200002",
    displayName: "Alcohol abuse",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 3,
  },
  {
    snomedCtCode: "26929004",
    displayName: "Alzheimer's disease",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 4,
  },
  {
    snomedCtCode: "87522002",
    displayName: "Anaemia - blood loss",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 5,
  },
  {
    snomedCtCode: "271737000",
    displayName: "Anaemia - deficiency",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 6,
  },
  {
    snomedCtCode: "194828000",
    displayName: "Angina pectoris",
    commonName: "Angina",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 7,
  },
  {
    snomedCtCode: "48694002",
    displayName: "Anxiety disorder",
    commonName: "Anxiety",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 8,
  },
  {
    snomedCtCode: "195967001",
    displayName: "Asthma",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 9,
  },
  {
    snomedCtCode: "73211009",
    displayName: "Diabetes mellitus",
    commonName: "Diabetes",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 10,
  },
  {
    snomedCtCode: "44054006",
    displayName: "Type 2 diabetes mellitus",
    commonName: "T2DM",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 11,
  },
  {
    snomedCtCode: "46635009",
    displayName: "Type 1 diabetes mellitus",
    commonName: "T1DM",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 12,
  },
  {
    snomedCtCode: "38341003",
    displayName: "Essential hypertension",
    commonName: "Hypertension",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 13,
  },
  {
    snomedCtCode: "13645005",
    displayName: "Chronic obstructive pulmonary disease",
    commonName: "COPD",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 14,
  },
  {
    snomedCtCode: "84757009",
    displayName: "Epilepsy",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 15,
  },
  {
    snomedCtCode: "22298006",
    displayName: "Previous myocardial infarction",
    commonName: "Previous MI",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 16,
  },
  {
    snomedCtCode: "230690007",
    displayName: "Cerebrovascular accident",
    commonName: "Previous stroke",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 17,
  },
  {
    snomedCtCode: "90708001",
    displayName: "Chronic kidney disease",
    commonName: "CKD",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 18,
  },
  {
    snomedCtCode: "235856003",
    displayName: "Chronic liver disease",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 19,
  },
  {
    snomedCtCode: "35489007",
    displayName: "Depressive disorder",
    commonName: "Depression",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 20,
  },
  {
    snomedCtCode: "414545008",
    displayName: "Ischaemic heart disease",
    commonName: "IHD",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 21,
  },
  {
    snomedCtCode: "84027008",
    displayName: "Heart failure",
    commonName: "CCF",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 22,
  },
  {
    snomedCtCode: "40930008",
    displayName: "Hypothyroidism",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 23,
  },
  {
    snomedCtCode: "34486009",
    displayName: "Hyperthyroidism",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 24,
  },
  {
    snomedCtCode: "64859006",
    displayName: "Osteoporosis",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 25,
  },
  {
    snomedCtCode: "396275006",
    displayName: "Osteoarthritis",
    commonName: "OA",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 26,
  },
  {
    snomedCtCode: "69896004",
    displayName: "Rheumatoid arthritis",
    commonName: "RA",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 27,
  },
  {
    snomedCtCode: "363346000",
    displayName: "Active malignancy",
    commonName: "Cancer",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 28,
  },
  {
    snomedCtCode: "414916001",
    displayName: "Obesity",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 29,
  },
  {
    snomedCtCode: "59282003",
    displayName: "Previous pulmonary embolism",
    commonName: "Previous PE",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 30,
  },
  {
    snomedCtCode: "128053003",
    displayName: "Previous deep vein thrombosis",
    commonName: "Previous DVT",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 31,
  },
  {
    snomedCtCode: "56265001",
    displayName: "Heart disease",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 32,
  },
  {
    snomedCtCode: "19829001",
    displayName: "Peripheral vascular disease",
    commonName: "PVD",
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 33,
  },
  {
    snomedCtCode: "86849004",
    displayName: "Dementia",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 34,
  },
  {
    snomedCtCode: "234532001",
    displayName: "Immunodeficiency",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 35,
  },
  {
    snomedCtCode: "77386006",
    displayName: "Pregnancy",
    commonName: null,
    category: "comorbidity",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 36,
  },
];

export const anaestheticTypeOptions: InsertSnomedRef[] = [
  {
    snomedCtCode: "50697003",
    displayName: "General anaesthesia",
    commonName: "GA",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 1,
  },
  {
    snomedCtCode: "386761002",
    displayName: "Local anaesthesia",
    commonName: "LA",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 2,
  },
  {
    snomedCtCode: "231249005",
    displayName: "Regional nerve block",
    commonName: "Regional block",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 3,
  },
  {
    snomedCtCode: "18946005",
    displayName: "Spinal anaesthesia",
    commonName: "Spinal",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 4,
  },
  {
    snomedCtCode: "18946005",
    displayName: "Epidural anaesthesia",
    commonName: "Epidural",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 5,
  },
  {
    snomedCtCode: "72641008",
    displayName: "Procedural sedation",
    commonName: "Sedation",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    sortOrder: 6,
  },
  {
    snomedCtCode: "72641008+386761002",
    displayName: "Sedation with local anaesthesia",
    commonName: "Sedation + Local",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    codeType: "internal",
    sortOrder: 7,
  },
  {
    snomedCtCode: "386761002+walant",
    displayName: "Wide awake local anaesthesia no tourniquet",
    commonName: "WALANT",
    category: "anaesthetic_type",
    subcategory: null,
    anatomicalRegion: null,
    specialty: null,
    codeType: "internal",
    sortOrder: 8,
  },
];

export const allSeedData: InsertSnomedRef[] = [
  ...vesselSeedData,
  ...flapTypeSeedData,
  ...donorVesselSeedData,
  ...compositionOptions,
  ...anatomicalRegionOptions,
  ...couplingMethodOptions,
  ...anastomosisConfigOptions,
  ...comorbidityOptions,
  ...anaestheticTypeOptions,
];
