import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Case, SPECIALTY_LABELS } from "@/types/case";

export interface PdfExportOptions {
  includePatientId?: boolean;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function formatDate(dateStr: string | undefined): string {
  if (!dateStr) return "";
  const [y, m, d] = dateStr.split("-");
  if (!y || !m || !d) return dateStr;
  return `${d}/${m}/${y}`;
}

function buildHtml(cases: Case[], options: PdfExportOptions): string {
  const now = new Date();
  const exportDate = `${now.getDate().toString().padStart(2, "0")}/${(now.getMonth() + 1).toString().padStart(2, "0")}/${now.getFullYear()}`;

  const dateRange =
    cases.length > 0
      ? `${formatDate(cases[cases.length - 1]?.procedureDate)} – ${formatDate(cases[0]?.procedureDate)}`
      : "";

  const headerCols = [
    "#",
    ...(options.includePatientId ? ["Patient"] : []),
    "Date",
    "Facility",
    "Specialty",
    "Primary Diagnosis",
    "Primary Procedure",
    "Complications",
    "Outcome",
  ];

  const rows = cases.map((c, idx) => {
    const primary = c.diagnosisGroups?.[0];
    const primaryProc = primary?.procedures?.[0];
    const complications = c.hasComplications
      ? (c.complications || [])
          .map((comp) => comp.clavienDindoGrade || "Yes")
          .join(", ")
      : "None";

    const cells = [
      String(idx + 1),
      ...(options.includePatientId
        ? [escapeHtml(c.patientIdentifier || "")]
        : []),
      formatDate(c.procedureDate),
      escapeHtml(c.facility || ""),
      escapeHtml(SPECIALTY_LABELS[c.specialty] || c.specialty),
      escapeHtml(primary?.diagnosis?.displayName || ""),
      escapeHtml(primaryProc?.procedureName || ""),
      escapeHtml(complications),
      escapeHtml(c.outcome || ""),
    ];

    return `<tr>${cells.map((cell) => `<td>${cell}</td>`).join("")}</tr>`;
  });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; font-size: 9px; color: #1F2328; }
  .header { padding: 16px 24px; border-bottom: 2px solid #E5A00D; margin-bottom: 12px; }
  .header h1 { font-size: 18px; font-weight: 700; color: #0C0F14; }
  .header .meta { font-size: 10px; color: #656D76; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 0 24px; }
  th { background: #0C0F14; color: #E6EDF3; font-weight: 600; font-size: 8px;
       text-transform: uppercase; letter-spacing: 0.5px; padding: 6px 8px; text-align: left; }
  td { padding: 5px 8px; border-bottom: 1px solid #D0D7DE; font-size: 9px; vertical-align: top; }
  tr:nth-child(even) td { background: #F6F8FA; }
  .footer { margin-top: 16px; padding: 12px 24px; font-size: 8px; color: #8B949E; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <h1>Opus — Surgical Case Export</h1>
    <div class="meta">${cases.length} cases · ${dateRange} · Exported ${exportDate}</div>
  </div>
  <table>
    <thead><tr>${headerCols.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
    <tbody>${rows.join("\n")}</tbody>
  </table>
  <div class="footer">Generated by Opus Logbook</div>
</body>
</html>`;
}

export async function exportCasesAsPdf(
  cases: Case[],
  options: PdfExportOptions = { includePatientId: true },
): Promise<void> {
  const html = buildHtml(cases, options);
  const { uri } = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(uri, {
    mimeType: "application/pdf",
    UTI: "com.adobe.pdf",
  });
}
